### ISSUE TITLE
Using the 'Lorem' generator with MacVim produces extra 'div' tag

### ISSUE THREAD

**Issue by ryentzer** [mattn/emmet-vim#136]
When in 'Insert' mode if I type `p>lorem` and expand it using `<c-y>,` I get the following code:

```
<p><div>Lorem . . . </div></p>
```

If I type `div>lorem` then the output is correct.
I'm using the latest MacVim

**Comment by skylite21** [comment]
This issue still persists, when I type lorem6 I get. 
`<div> Amet ea atque nobis sint doloribus </div>`

Is it possible to turn off the extra div somehow?

**Comment by gilgameshskytrooper** [comment]
I think u gotta do like `p>lorem6` for `<p>Amet animi consequuntur nemo magni excepturi. Commodi quidem possimus expedita doloremque eos, neque? Incidunt minima obcaecati nostrum porro autem. Consequatur</p>`.

By itself, it will assume you want it in a div.

**Comment by skylite21** [comment]
Thanks, this is ok in some cases but sometimes I don't want any wrapper and just need the lorem ipsum text so then I need to delete the div it assumes.

**Comment by mattn** [comment]
```
<c-r>=emmet#lorem#en#expand("50lorem")
```

**Comment by skylite21** [comment]
@mattn can you explain what you mean by this? How/where should I use this line?

**Comment by mattn** [comment]
You can insert 50 lorem(s) without html tags using the way above.

**Comment by skylite21** [comment]
Thanks this works too but its actually more typing than just expanding 50lorem and deleting the extra div.

**Comment by mattn** [comment]
Ah, emmet seems to change this behavior. I tried this on https://docs.emmet.io/ in few month ago. And the playground expand lorem with div tag. Okay, should be fixed.

**Comment by skylite21** [comment]
If it's any help I noticed on https://docs.emmet.io/ the extra div tag only appears when you do `lorem5*` if you leave out the `*` the div will not be added.

**Comment by mattn** [comment]
Fixed in last commit.
