### ISSUE TITLE
Unable to change numbering base and direction by abbreviations: "ul>li.item$@3*5" and "ul>li.item$@-3*5"

### ISSUE THREAD

**Issue by dkozlov** [mattn/emmet-vim#144]
According to http://docs.emmet.io/abbreviations/syntax/

1) To change counter base value, add @N modifier to $:

ul>li.item$@3*5

…transforms to
`<ul>
    <li class="item3"></li>
    <li class="item4"></li>
    <li class="item5"></li>
    <li class="item6"></li>
    <li class="item7"></li>
</ul>`

2) You can use these modifiers together:

ul>li.item$@-3*5

…is transformed to

`<ul>
    <li class="item7"></li>
    <li class="item6"></li>
    <li class="item5"></li>
    <li class="item4"></li>
    <li class="item3"></li>
</ul>`

[Expected result]

1)
`<ul>
    <li class="item3"></li>
    <li class="item4"></li>
    <li class="item5"></li>
    <li class="item6"></li>
    <li class="item7"></li>
</ul>`
2)
`<ul>
    <li class="item7"></li>
    <li class="item6"></li>
    <li class="item5"></li>
    <li class="item4"></li>
    <li class="item3"></li>
</ul>`

[Actual result]

`<ul>
    <li class="item1"></li>
</ul>`

**Comment by Funyapu** [comment]
Hi @mattn! I think this issue has been reproduced again.
I tried w/ @dkozlov's sample, but still get the numbers in order, not desc.
My vim version is 7.4.488, the one installed in Mac originally. 

``` testCode
ul>li.item$@-*5
```

``` result
<ul>
  <li class="item1"></li>
  <li class="item2"></li>
  <li class="item3"></li>
  <li class="item4"></li>
  <li class="item5"></li>
</ul>
```

**Comment by mattn** [comment]
I can't repro

```
<ul>
    <li class="item5"></li>
    <li class="item4"></li>
    <li class="item3"></li>
    <li class="item2"></li>
    <li class="item1"></li>
</ul>
```

**Comment by Funyapu** [comment]
I'm trying with the other Mac, but still get the same...
Is there any setting I have to set?
