### ISSUE TITLE
How to enable expansion with tab key 

### ISSUE THREAD

**Issue by medinLaVie** [mattn/emmet-vim#149]
I did according to the previous post on this question but the codes didn't work for me. 

```
 let g:user_zen_leader_key = '<C-Z>'
 50  autocmd FileType html,xhtml,tt2,tt2html,css imap <buffer> <Tab> <C-Z>, | imap <buffer> <C-N> <C-Z>n
```

Thanks!

**Comment by yetingsky** [comment]
@zhongqf do you have any idea now for making it work in insert mode?
