### ISSUE TITLE
Can't change key mapping to tab

### ISSUE THREAD

**Issue by SephVelut** [mattn/emmet-vim#154]
`let: g:user_zen_leader_key: syntax error in expression (error token is ":user_zen_leader_key")`

I tried `let g:user_zen_leader_key = '<tab>'`

Any ideas?

**Comment by jedrekdomanski** [comment]
> BTW, `g:user_emmet_leader_key` is meaning of leading key to replace `<c-y>,` to `<tab>,`. So you need to typoe comma after typing `<c-y>`.
> If you just want to expand with `<tab>` key, try following.
> 
> ```
> let g:user_emmet_expandabbr_key = '<tab>'
> ```

This doesn't work. What is worse, with this line I have to press 2*TAB to make an indentation. Expanding html tags doesn't work, at least in .js files.

**Comment by GopherJ** [comment]
it doesn't work for me neither
