### ISSUE TITLE
Update image size in css

### ISSUE THREAD

**Issue by andreiglingeanu** [mattn/emmet-vim#155]
Implement please emmet#lang#css#imageSize().
Or give me some tip on how to add a property to current rule.
I know how to get image size, looked from html version of this function.

Thanks!

**Comment by andymabb** [comment]
Would be really good if this worked for avif format images

**Comment by mattn** [comment]
Please install identify command provided by imagemagick.

**Comment by mattn** [comment]
Ah, you want to use avif in data scheme? okay, will look into in later.

**Comment by mattn** [comment]
Now supported avif.
