### ISSUE TITLE
Having a Sublime Text-like functionality

### ISSUE THREAD

**Issue by greduan** [mattn/emmet-vim#159]
@mattn 
Thanks for this awesome plugin. :)

I just wanted some advice on what would be the best way to achieve this with emmet-vim.

In Sublime Text's version of the Emmet plugin the tab key expands the expression, if it's valid, otherwise it enters a tab character (or four spaces).

What would be the best way to achieve this? Or would it be something that has to be implemented into emmet-vim?

Thanks! :)

**Comment by adrianoavelino** [comment]
@ConnorAtherton  are you got emmet and supertab?
