### ISSUE TITLE
Expansion with tab key is buggy

### ISSUE THREAD

**Issue by reywright** [mattn/emmet-vim#168]
So getting tab to work is half of it:

```
autocmd FileType html,htmldjango,css,scss,sass imap <tab> <plug>(EmmetExpandAbbr)
```

But the thing is... I still want to be able to use tab for it's normal functionality. Meaning... I want to be able to use tab to indent code in insert mode... I want to be able to even use tab to start typing a certain amount in... and right now, emmet isn't really allowing that.

**Comment by sandboxws** [comment]
@darvelo your snippet works but I'm facing a problem, not sure if it's related to emmet-vim or something in my vimrc is causing this issue. Consider the following example

I type ul>li*5 then hit tab, it expands correctly and I'm able to tab through list items, but after reaching the last list item and then hitting tab, instead of moving the cursor right after the ul closing tag, it moves to any empty double quotes available on the page ?!

Anyone can help with this?

Note: I'm using NeoSnippets

**Comment by mattn** [comment]
@sandboxws could you please show me screencast or something to reproduce easier?

**Comment by sandboxws** [comment]
@mattn here you go https://www.dropbox.com/s/keg9bmaxy03e4xo/emmet_neosnippet.mov?dl=0
sorry for the unregistered watermark :)

**Comment by mattn** [comment]
@sandboxws 
```
<ul>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
	<li><!-- CURRENT --></li>
</ul>
<!-- HERE? -->
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    
</body>
</html>
```
Do you expect to jump to `HERE` from `CURRENT`?

**Comment by sandboxws** [comment]
@mattn in ST3 it jumping ends at  so I expect jumping to end at either  or

**Comment by mattn** [comment]
Hmm, I'm thinking, I like current behavior. So I'll provide another `<plug>` mapping to do it.

**Comment by sandboxws** [comment]
@mattn thanks man!

**Comment by mattn** [comment]
@sandboxws well, this is not depend on ultisnip, neosnippet, etc, i think. right?

**Comment by sandboxws** [comment]
@mattn yes, it should be independent of snippet plugin.

**Comment by darvelo** [comment]
@mattn Thanks for the update!

@sandboxws I'm not sure here.. are you still using the snippet I posted after this change, or is there a better way to do this? In either case I updated my snippet to use emmet's `<Plug>` variables rather than hardcoding the default emmet key.

**Comment by sandboxws** [comment]
@darvelo thanks for updating your function, but unfortunately the issue still exists.

**Comment by darvelo** [comment]
@sandboxws Oh, I see what you're saying. That's a vim-emmet thing, but I think being able to jump between empty quotes or tags elsewhere could be useful. What's the purpose of pressing `<Tab>` at the end of your `<li>` set?

@mattn I saw you added a `<Plug>(emmet-move-next-item)` and I tried to use it, but it jumps someplace else and puts me in visual mode. Not sure if that feature is related to this issue?

**Comment by darvelo** [comment]
For posterity, I've expanded my above snippet to map `Tab` and `Shift+Tab` for going between emmet fields, and `Ctrl+s` for expansion. If you use `Ctrl+s` in terminal vim you'll need a line in your `.bashrc` as noted below:

```viml
" tab through emmet fields
function! s:move_to_next_emmet_area(direction)
  " go to next item in a popup menu
  if pumvisible()
    if (a:direction == 0)
      return "\<C-p>"
    else
      return "\<C-n>"
    endif
  endif

  " try to determine if we're within quotes or angle brackets.
  " if so, assume we're in an emmet fill area.
  let line = getline('.')
  if col('.') < len(line)
    let line = matchstr(line, '[">][^<"]*\%'.col('.').'c[^>"]*[<"]')

    if len(line) >= 2
      if (a:direction == 0)
        return "\<Plug>(emmet-move-prev)"
      else
        return "\<Plug>(emmet-move-next)"
      endif
    endif
  endif

  " return a regular tab character
  return "\<tab>"
endfunction

" expand and emmet sequence like ul>li*5
function! s:expand_emmet_sequence()
  " first try to expand any neosnippets
  if neosnippet#expandable_or_jumpable()
    return "\<Plug>(neosnippet_expand_or_jump)"
  endif

  " expand anything emmet thinks is expandable
  if emmet#isExpandable()
    return "\<Plug>(emmet-expand-abbr)"
  endif
endfun

" using <C-s> requires a line in .bashrc/.zshrc/etc. to prevent
" linux terminal driver from freezing the terminal on ctrl-s:
"     stty -ixon -ixoff
" see: http://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal#12108
" also: http://stackoverflow.com/questions/6429515/stty-hupcl-ixon-ixoff
autocmd FileType html,hbs,handlebars,css,scss imap <buffer><expr><C-s> <sid>expand_emmet_sequence()
autocmd FileType html,hbs,handlebars,css,scss imap <buffer><expr><S-TAB> <sid>move_to_next_emmet_area(0)
autocmd FileType html,hbs,handlebars,css,scss imap <buffer><expr><TAB> <sid>move_to_next_emmet_area(1)
```

**Comment by reywright** [comment]
I'm going to go ahead and close this ticket. I don't use this plugin anymore and it's been 4 years since I opened it, and it's very general to begin with.
