### ISSUE TITLE
Is it possible to add custom snippets?

### ISSUE THREAD

**Issue by lifeBalance** [mattn/emmet-vim#197]
According to the [emmet documentation](http://docs.emmet.io/customization/snippets/) it is possible to add customized snippets using snippets.json.
Is that possible with emmet-vim?

**Comment by JuanVqz** [comment]
Hi everyone. I want add my snippets but I can't. 

I install web-api and last I put this line on my vimrc and show this error when source .vimrc

Show this error:
Error detected while processing function webapi#json#decode:
line   33:
E15: Invalid expression: 
E15: Invalid expression: 

sorry for my english. thanks for your help!

**Comment by mattn** [comment]
please show me your configuration?

**Comment by JuanVqz** [comment]
Hi mattn thanks.

I have installed
---
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
	Plugin 'VundleVim/Vundle.vim'

	Plugin 'mattn/emmet-vim'
	Plugin 'mattn/webapi-vim'
call vundle#end()
filetype plugin indent on
---
 I write this line in my vimrc
let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.vim/snippets.json')), "\n"))

then charge vimrc with " source ~ / .vimrc "

It shows me the following error:

Error detected while processing function webapi#json#decode:
line   33:
E15: Invalid expression: 
E15: Invalid expression: 

and it does not work.

**Comment by mattn** [comment]
please show me your `snippets.json`.

**Comment by JuanVqz** [comment]
Is empty, my friend.

**Comment by mattn** [comment]
empty is not valid JSON.

**Comment by JuanVqz** [comment]
I wrote this in my snippets.json : 
{¬
    "html": {¬
        "filters": "html",¬
        "profile": "html",¬
        "snippets": {¬
            "hi": "hi my friend"¬
        }¬
    }¬
}¬
and when I run it in index.html "Hi <C -y> , " shows this error.

=emmet#expandAbbr(0,"")
Error detected while processing function emmet#expandAbbr[153]..emmet#parseIntoTree[4]..emmet#lang#h
tml#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emme
t#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[11
8]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseInt
oTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#
parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#la
ng#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..
emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTre
e[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#pars
eIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#h
tml#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emme
t#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[11
8]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseInt
oTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#
parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#la
ng#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..
emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTre
e[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#pars
eIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#h
tml#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emme
t#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[11
8]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseInt
oTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#parseIntoTree[118]..emmet#lang#html#
-- More --

**Comment by JuanVqz** [comment]
I tested the same in php and it works. = P

**Comment by JuanVqz** [comment]
Last login: Tue May 24 19:22:45 on ttys001
➜  ~ vim .vimrc 
➜  ~ ls
Applications   Documents      Dropbox        Movies         Pictures       Sites
Desktop        Downloads      Library        Music          Public         VirtualBox VMs
➜  ~ cd Desktop 
➜  Desktop ls
210516_milenio_121728.asf 210516_teaser_oro.asf     ch03_20160505150118.mp4
➜  Desktop vim index.html
➜  Desktop ls
210516_milenio_121728.asf 210516_teaser_oro.asf     ch03_20160505150118.mp4
➜  Desktop cd
➜  ~ vim .vim/snippets.json 
➜  ~ source .vimrc 
.vimrc:3: command not found: filetype
.vimrc:9: command not found: Plugin
.vimrc:10: command not found: Plugin
.vimrc:11: command not found: Plugin
.vimrc:12: command not found: Plugin
.vimrc:13: command not found: Plugin
.vimrc:14: command not found: Plugin
.vimrc:15: command not found: Plugin
.vimrc:16: command not found: Plugin
.vimrc:17: command not found: Plugin
.vimrc:18: command not found: Plugin
.vimrc:19: command not found: Plugin
.vimrc:20: command not found: Plugin
.vimrc:21: command not found: Plugin
.vimrc:25: command not found: syntax
.vimrc:27: command not found: colorscheme
.vimrc:35: command not found: 4
.vimrc:40: no such file or directory: rb/js
.vimrc:41: command not found: autocmd
.vimrc:42: command not found: autocmd
.vimrc:44: command not found: cursor
Tabs: and: invalid tab stop
.vimrc:49: parse error near `<'
➜  ~ vim .vimrc 
➜  ~ vim .vimrc
➜  ~ source .vimrc 
.vimrc:3: command not found: filetype
.vimrc:9: command not found: Plugin
.vimrc:10: command not found: Plugin
.vimrc:11: command not found: Plugin
.vimrc:12: command not found: Plugin
.vimrc:13: command not found: Plugin
.vimrc:14: command not found: Plugin
.vimrc:15: command not found: Plugin
.vimrc:16: command not found: Plugin
.vimrc:17: command not found: Plugin
.vimrc:18: command not found: Plugin
.vimrc:19: command not found: Plugin
.vimrc:20: command not found: Plugin
.vimrc:21: command not found: Plugin
.vimrc:25: command not found: syntax
.vimrc:27: command not found: colorscheme
.vimrc:38: command not found: autocmd
.vimrc:39: command not found: autocmd
.vimrc:43: parse error near `<'
➜  ~ vim .vimrc   
➜  ~ clear

                                                                                                    
























➜  ~ vim .vim/snippets.json 
➜  ~ cd Desktop 
➜  Desktop vim index.php
➜  Desktop clear





















                                                                                                                  



























➜  Desktop cd
➜  ~ vim .vim/snippets.json 
➜  ~ cd Desktop 
➜  Desktop mvim index.blade.php
➜  Desktop clear























                                                                                                                                                            



























➜  Desktop cd
➜  ~ vim .vim/snippets.json 



















but not work this...

`{
	"php": {
		"filters": "php",
		"profile": "php",
		"snippets": {
			"cnd": "<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css'>"
		}
	}
}
`
