### ISSUE TITLE
css: tab vs space

### ISSUE THREAD

**Issue by metainfa** [mattn/emmet-vim#201]
For example I created the "main.css" file. Then in it I write:
`body`
Press Ctrl+y,
and here that occurs:

`body {
tab symbol 
}`

I assumed that will be
`body {
space symbol
}`

.vimrc:
`let g:user_emmet_settings = {
\ 'indentation' : '  '
\}`

I corrected a line 24 in file:
 https://github.com/mattn/emmet-vim/blob/master/autoload/emmet/lang/css.vim 
from: 
         `let current.snippet = abbr . " {\n\t${cursor}\n}"` 
to: 
         `let current.snippet = abbr . " {\n" . indent . "${cursor}\n}"`

With the changed line work fine.

**Comment by carlesso** [comment]
Without opening a new issue, is there and handy way to do the same in html files?

**Comment by mattn** [comment]
what is your issue?

**Comment by carlesso** [comment]
Let's say if I do

```
ul>il*4
```

And `<C-y>,` I will end with:

```
<ul>
\t<li></li>
\t<li></li>
</ul>
```

But I'ld like to have
```
<ul>
  <li></li>
  <li></li>
</ul>
```

Using spaces instead of tabs.

**Comment by mattn** [comment]
maybe you specify `'\t'` instead of `"\t"` in g:user_emmet_settings.

**Comment by carlesso** [comment]
Didn't know about `g:user_emmet_settings`, thanks!

Found around the internet this:
```
let g:user_emmet_settings = {
\  'html' : {
\    'indentation' : '  '
\  }
\}
```
