### ISSUE TITLE
not work with vim 7.2

### ISSUE THREAD

**Issue by cckowin** [mattn/emmet-vim#214]
when the line is

	aaaaaaaaaa

visual select it and using `^Y,test` it became this

	<test>^Maaaaaaaaaa</test>

test.vim

	let str= "aaaaaaaaaa"
	let expand = "<test>$#${cursor}</test>"
	let expand = substitute(expand, '\$#', '\="\n" . str', 'g')
	echo expand

on vim 7.2

	execute `ex -N -u NONE -S test.vim`

it display

	aaaaaaaaaa${cursor}</test>
	Entering Ex mode.  Type "visual" to go to Normal mode.

on vim 7.3

	execute `ex -N -u NONE -S test.vim`

it display

	<test>
	aaaaaaaaaa${cursor}</test>
	Entering Ex mode.  Type "visual" to go to Normal mode.

**Comment by barwinco** [comment]
vim 7.**4** was released before you opened this issue, so...

**Comment by mattn** [comment]
https://github.com/mattn/emmet-vim/commit/25d321c66fd7b0358ccb3bb2c95be5a0f332d10c

done
