### ISSUE TITLE
<Plug>(emmet-expand-abbr) & YCM

### ISSUE THREAD

**Issue by ahmedelgabri** [mattn/emmet-vim#232]
I use YCM for autocompletion & I disable Emmet in JavaScript files, but whenever I try to use tab with YCM I get this `<Plug>(emmet-expand-abbr)` any Idea how can I fix this & use tab for both of them?

This is my Emmet settings & YCM settings

```
" Emmet
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")
let g:user_emmet_next_key='<C-n>'

" YCM
let g:ycm_autoclose_preview_window_after_completion = 0
```

**Comment by carlesandres** [comment]
I am using Ultisnips for autocompletion and happen to experience something similar. I have the following emmet config: 
```
" Use emmet only for html and css files
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall

" from :h zencoding-customize-keymappings
let g:user_emmet_leader_key='<C-Z>'
imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")

"let g:user_zen_expandabbr_key = '<c-e>'
let g:user_emmet_complete_tag = 1

let g:user_emmet_settings = {
  \  'scss' : {
  \    'filters' : 'fc',
  \  }
  \}
```

UltiSnips autocompletion with TAB works fine until I use emmet-vim. After using emmet-vim for a while,  I cannot use Ultisnips anymore and I get `<Plug>(emmet-expand-abbr)` when trying to expand a snippet in, for example, a JS file.

**Comment by mattn** [comment]
I tried emmet & ultisnips. But I can't reproduce your issue. Could you pleaes try it withou YCM.

**Comment by cjnucette** [comment]
You should use "<buffer>" so it only affects the current buffer:
`imap <buffer> <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")`

**Comment by lionize** [comment]
I'm not using YCM or UltiSnips. I have the same line that cjnucette posted and it is inserting `<Plug>(emmet-expand-abbr)` anytime I attempt to use tab to expand an abbreviation.

**Comment by yukihiratype2** [comment]
```
let g:user_emmet_install_global = 0
autocmd FileType html,css  EmmetInstall
autocmd FileType html,css imap <TAB> <plug>(emmet-expand-abbr)
```

I used have this problem ,but I add **autocmd FileType** before imap <TAB> <plug>(emmet-expand-abbr),and the problem is gone
