### ISSUE TITLE
add `link:import` for webcomponents

### ISSUE THREAD

**Issue by kashiro** [mattn/emmet-vim#234]
add `link:import` for [webcomponents](http://www.w3.org/TR/components-intro/)

**Comment by craftgear** [comment]
link:im doesn't expand itself as <link rel="import>.
Is this happening only to me?

**Comment by kashiro** [comment]
@craftgear 

My `emmet-vim` worked well.
Would you make plugin update ?

**Comment by craftgear** [comment]
Gotcha, I'll give it a shot.
It's good to know the problem is on my side.

Thanks.

**Comment by craftgear** [comment]
Hi, I confirmed that the problem was caused by a predecessor plugin 'mattn/zencoding-vim'.
After I deleted it 'link:im' and 'link:import' works as expected.
