### ISSUE TITLE
incorrect custom abbreviation behavior

### ISSUE THREAD

**Issue by aoberoi** [mattn/emmet-vim#237]
i've loaded custom abbreviations using the suggested approach that uses webapi-vim. this is in my .vimrc:

```
let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.emmet/snippets.json')), "\n"))
```

the `~/.emmet/snippets.json` file contains the following:

```javascript
{
  "html": {
    "abbreviations": {
      "script:ot": "script:src[src=//static.opentok.com/webrtc/v2.2/js/opentok.min.js]",
      "script:ot1": "script:src[src=//static.opentok.com/v1.1/js/TB.min.js]"
    }
  }
}
```

using this plugin before expansion i have:

```
script:ot
```

and after:

```
<script:ot></script:ot>
```

for comparison, if i use the official emmet plugin in the Atom editor the after looks right:

```
<script src="//static.opentok.com/webrtc/v2.2/js/opentok.min.js"></script>
```

**Comment by bennettrogers** [comment]
I'm seeing this same issue. Custom snippets will expand as expected, but custom abbreviations are ignored and just expand to a simple tag like @aoberoi is experiencing.

**Comment by bennettrogers** [comment]
From what I can tell, it looks like emmet-vim doesn't have handling for abbreviations, only snippets. Is that correct? If I need to make my custom expansion as a snippet instead of an abbrevation I think that will work fine. It's just that I was going crazy trying to figure out why simple abbreviations weren't working, only to look at the source and figure out that it's only processing snippets.

@mattn would you mind just confirming if that's the case? Thank you!

**Comment by mattn** [comment]
Then do you need to separate
* snippet to snippet
* snippet to html
Right?

**Comment by bennettrogers** [comment]
I'm sorry, I'm not sure I understand your question.

I mean that the original emmet.io has separate handling for snippets and abbreviations. For example, the [expansion for html:5](https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L835) is an abbreviation. But it looks like those have all been translated to snippets for emmet-vim.

Do snippets in emmet-vim support the use cases of both snippets and abbreviations from the original emmet.io?

**Comment by mattn** [comment]
abbreviation contains snippet and abbreviation

https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L702
https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L830
