### ISSUE TITLE
Option to replace expansion attributes wrapping double quotes with single-quote or no quotes

### ISSUE THREAD

**Issue by zanona** [mattn/emmet-vim#239]
When expanding tags with `link` <kbd>ctrl</kbd>-<kbd>y</kbd><kbd>,</kbd> for example.

The following is expanded:

``` html
<link rel="stylesheet" href="">
```

Is there any way to configure emmet-vim to use single quotes or no quotes at all for attribute wrapping? considering these are also valid html styles?

**Comment by zanona** [comment]
hey @mattn has the syntax for this option changed? It doesn't seem to be working anymore?

**Comment by mattn** [comment]
Not
```
let g:user_emmet_settings = {'html':{'quote_char': "",},}
```
It's
```
let g:user_emmet_settings = {'html':{'quote_char': "'",},}
```

**Comment by zanona** [comment]
@mattn yes, I understand. However previously I could just set it to the example mentioned if I wanted unquoted attributes like 

```html
<a href=# class=test>link</a>
```

However now it doesn't seem to work anymore?

**Comment by zanona** [comment]
hey @mattn any ideas? I would like to output attributes without quotes. thanks

**Comment by mattn** [comment]
fixed https://github.com/mattn/emmet-vim/commit/abdf10e91c9227f282bd6e635e491beda6719166

**Comment by zanona** [comment]
That's great. Thanks a lot :)

**Comment by kevinisaac** [comment]
How do we do this for JS files? I tried `js`instead of `html` but with no luck.

**Comment by kevinisaac** [comment]
Regarding my previous comment, just tried `javascript` instead of `js` and it works. Looks like it refers to the file type and not the file extension. This hopefully helps someone having the same issue.
