### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by th0th** [mattn/emmet-vim#248]
Hello,

First of all, this is my .vimrc: https://gist.github.com/th0th/ecea66dadee65dce9cac

When I try to expand a tag, let's say html ('_' is the cursor):

```
html_
```

then i press `<C-y>,` it expands to this:

```
<html>_</html>
```

however, i expect it to be:

```
<html>
    _
</html>
```

also even when I press enter when it is like this:

```
<html>_</html>
```

it should be indented like my previous code, however when I press enter I get this:

```
<html>
_</html>
```

I am not sure what I am doing wrong, can you please help?

**Comment by davidlowryduda** [comment]
I'm just trying out emmet for the first time. I have the same behaviour.

**Comment by mattn** [comment]
Could you please try this change? https://github.com/mattn/emmet-vim/commit/8b9bcac7a03cabc0cd7cace8bb00b8c22884d98e

**Comment by th0th** [comment]
Hi @mattn, tried the change, didn't change anything here.

**Comment by mattn** [comment]
did you set indent_blockelement=1 like below?

```
    let g:user_emmet_settings = {
    \  'html' : {
         ... snip...
    \    'indent_blockelement': 1,
         ... snip...
    \  },
    \}
```

**Comment by zanona** [comment]
Is there any way to also apply this to inline elements?

```html
<label>
    <span>Title</title>
    <input name=foo>
</label>
```
is a common inline snippet for me.

**Comment by tomatosource** [comment]
Anyone have any luck forcing closing tags on new lines?

**Comment by mattn** [comment]
https://github.com/mattn/emmet-vim/commit/2247b1f457cd677d911c0a233f5e2e75c9ff908e should fix this. if you still have issue, please file new issue.
