### ISSUE TITLE
webApi-vim not working when include the custom snippets.json file

### ISSUE THREAD

**Issue by mc-zone** [mattn/emmet-vim#250]
Hi, mattn.
There are something wrong when I include the custom `snippets.json` file into `~/.vimrc`.
I have installed the webApi-vim using pathogen(git clone the webApi-vim into `~/.vim/bundle`), and add this line to the  ~/.vimrc :
```
let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.snippets.json')), "\n"))
```
but when I open my vim,  this error is displayed:
```
Error detected while processing /Users/mc-zone/.vimrc:
line   47:
E117: Unknown function: webapi#json#decode
E15: Invalid expression: webapi#json#decode(join(readfile(expand('~/.snippets.json')), "\n"))
```
Although I copy some custom abbreviations into the `.snippets.json`, this is still not working.
I don't know where the error occurred. Can you give me some advice?

**Comment by mattn** [comment]
Maybe you don't install webapi-vim

**Comment by mc-zone** [comment]
I just copyed the file from `webapi-vim/autoload/` to `~/.vim/autoload/` manually, and this problem was solved. Maybe there is something wrong with my pathogen. It's so weird. 
Anyway, really thanks for you reply.
