### ISSUE TITLE
Html lang attribute isn't changed

### ISSUE THREAD

**Issue by shigo141** [mattn/emmet-vim#253]
I tried the following settings, but it was ignored.

```vim
let g:user_emmet_settings = { 'lang' : 'ja' }
```
I think this bug is introduced in [2a8f0e0](https://github.com/mattn/emmet-vim/commit/2a8f0e094d3fae2ef081db873af3c3835f271280)

**Comment by mattn** [comment]
No this is not a bug. official emmet moves them into `variables` in structure.

**Comment by shigo141** [comment]
Thanks, i got it
