### ISSUE TITLE
JSX Support

### ISSUE THREAD

**Issue by edygar** [mattn/emmet-vim#255]
Is there anyway to change 'class' to 'className' while expanding notations in *.jsx files?

**Comment by mattn** [comment]
What you expect behavior? Could you please show me BEFORE and AFTER.

**Comment by edygar** [comment]
there are few differences about the actual HTML to the JSX, but the more important are the following:
Expanding `form.class-name#anyId>(label>input:text)+input:submit`
```html
<form id="anyId" class="class-name" action="">
  <label for=""><input id="" type="text" name=""></label>
  <input type="submit" value="">
</form>
```
but in JSX it would be
```html
<form id="anyId" className="class-name" action="">
  <!-- attr for becomes forName -->
  <label forName="">
      <!-- Self-closing tags as full xml  -->
    <input id="" type="text" name=""/>
  </label>
  <input type="submit" value=""/>
</form>
```
Any other doubts you might have, there is an online conversor: http://facebook.github.io/react/html-jsx.html

**Comment by edygar** [comment]
You are the best ;D

**Comment by jarodtaylor** [comment]
Is there a way to enable this in .js files using .jsx? I'm okay with it being this way in all .js files. I never use this kind of markup in .js files that aren't .jsx, anyway.

**Comment by mattn** [comment]
try to set filetype to `javascript.jsx`.

**Comment by joakimmohn** [comment]
Did it work for you? i have same problem but that didnt seem to work

**Comment by jarodtaylor** [comment]
I had to update my version of emmet, and then any file with the .jsx extension worked. However, in order to get it to work inside of my .js files (I don't always name my React Components ****.jsx) I had to do this on each .js file:

```
:set filetype:javascript.jsx
```

**Comment by mattn** [comment]
If you don't want to set filetype=javascript.jsx or getting something problems, please put following into your vimrc.

```vim
let g:user_emmet_settings = {
\  'javascript' : {
\      'extends' : 'jsx',
\  },
\}
```

**Comment by joakimmohn** [comment]
my emmet works fine with html files, but it doesn't work with any other
filetype. Even if i write :set filetype=javascript. any idea what is wrong?

**Comment by jarodtaylor** [comment]
@joakimmohn have you gone into your bundle and updated master for emmet-vim?

**Comment by danilobjr** [comment]
@mattn Can I do something like this in my .vimrc? (include only html, css and jsx files)
This is not working.

```
let g:user_emmet_install_global=0
autocmd FileType html,css,jsx EmmetInstall
```

**Comment by mattn** [comment]
@danilobjr what do you mean `not working`?

**Comment by danilobjr** [comment]
@mattn Sorry. Let me be more clear. With these 2 lines, I have emmet working only on html and css files.
```
let g:user_emmet_install_global=0
autocmd FileType html,css EmmetInstall
```
But if I include jsx, like below, I dont have emmet working in my jsx files. Only on html and css.
```
autocmd FileType html,css,jsx EmmetInstall
```

**Comment by mattn** [comment]
Maybe your jsx filetype is `javascript`. Please confirm like below.

```
:e foo.jsx
:set ft?
```

**Comment by danilobjr** [comment]
@mattn result is
```
filetype=javascript.jsx
```

**Comment by mattn** [comment]
Then you should do:

```vim
autocmd FileType html,css,javascript.jsx EmmetInstall
```

**Comment by danilobjr** [comment]
@mattn Thank you so much! =]

**Comment by anthonybrown** [comment]
I can't seem to get emmet-vim to expand `class` to `className`
How can I debug this? I followed all of the suggestions in this post and nothing seems to be working for me? [here is my .vimrc] file(https://github.com/anthonybrown/my-dotfiles/blob/master/vimrc)

**Comment by mattn** [comment]
1. open foo.jsx
2. make sure `set filetype?` is `jsx`
3. type `foo.bar` and confirm expand to `<foo className="bar"></foo>`

![emmet](https://cloud.githubusercontent.com/assets/10111/20245229/36596afc-a9e0-11e6-9945-bd1e049d8a5b.gif)

**Comment by anthonybrown** [comment]
My filetypes are JavaScript though

**Comment by mattn** [comment]
Because you do not set. Changing filetype is not a task of emmet-vim.

**Comment by anthonybrown** [comment]
https://asciinema.org/a/c9x86d3d30decdt9wvt8droz9

**Comment by anthonybrown** [comment]
@mattn when i check the filetype it says `jsx` what am I missing?

Thanks

**Comment by mattn** [comment]
Do you use latest version?

**Comment by anthonybrown** [comment]
yes, I just did a `git pull` to make sure, and I'm using `vim v8.x`

**Comment by anthonybrown** [comment]
![screenshot 2016-11-13 21 19 54](https://cloud.githubusercontent.com/assets/1719818/20251381/efb4b640-a9e6-11e6-8a68-7999313f2234.png)

**Comment by mattn** [comment]
please try below on the jsx file.

```
:echo emmet#getFileType()
```

What value do you get?

**Comment by anthonybrown** [comment]
`xmlAttrib`

**Comment by mattn** [comment]
Maybe your filetype is not jsx.

**Comment by anthonybrown** [comment]
@mattn when I do `set fs?` I am getting `filetype=javascript.jsx`
Maybe another plugin is not working?

**Comment by anthonybrown** [comment]
this is strange, now I'm getting `fsync` when doing `:set fs ?`

**Comment by kaylacohn** [comment]
@anthonybrown having the same issue, when I do `:set ft=jsx` the expansion works correctly however it breaks syntax highlighting. However, if I have the filetype set to `javascript.jsx` it doesn't user `className`

**Comment by mattn** [comment]
what plugin do you use for syntax?

On 11/20/16, Kayla Cohn <notifications@github.com> wrote:
> @anthonybrown having the same issue, when I do `:set ft=jsx` the expansion
> works correctly however it breaks syntax highlighting. However, if I have
> the filetype set to `javascript.jsx` it doesn't user `className`
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/emmet-vim/issues/255#issuecomment-261760326


-- 
- Yasuhiro Matsumoto

**Comment by anthonybrown** [comment]
I'm using `vim-jsx`, `vim-es6`, `emmet-vim`, `syntastic`, `tabular`, `tlib-vim`, `vim-addon-mw-utilils`, `vim-surround`, `vim-stylus`, `vim-scss`, `vim-javascript`, `tender`, `vim-fugative`, `vim-node`, `vim-stylus`, `vim-mustache-handlebars` `vim-pug`, `autopairs`, vim snippets and snipmate, nerdcommenter, nerdtree-git-plugin 
I think those are all the styling plugins, I do have some for colors but those are the main syntax related plugins and some that I added that might interfere with `emmet-vim`

**Comment by kaylacohn** [comment]
@mattn I'm using `vim-nerdtree-syntax-highlight`, `vim-surround`,  `emmet-vim`,  `MatchTag`,  `html5.vim`, `vim-javascript`, `vim-node`, `vim-angular`, `javascript-libraries-syntax.vim`, `vim-jsx`, `vim-json`, `vim-mustache-handlebars`, `vim-jade`, `scss-syntax.vim`, `vim-stylus`, `vim-less`, `vim-css-color`, `vim-css3-syntax`,

**Comment by git-toni** [comment]
@kaylacohn That looks like a solution, somehow defining those "alias". But how do you add those custom config to `vim-jsx` in `vimrc`, what syntax? Would you mind pasting your `.vimrc`?

**Comment by kaylacohn** [comment]
@git-toni `Plug 'mxw/vim-jsx', { 'for': 'jsx' } " JSX support`
This is the change that matters `Plug 'mattn/emmet-vim', { 'for': ['javascript.jsx', 'html', 'css'] } " `

**Comment by anthonybrown** [comment]
@kaylacohn where are you doing this, in the .vimrc file

**Comment by kaylacohn** [comment]
@anthonybrown yes in my `.vimrc`. I handle installing plugins at the very top.

Here is a pic:
<img width="1399" alt="screen shot 2016-11-20 at 3 15 56 pm" src="https://cloud.githubusercontent.com/assets/12119723/20484211/1bbd9468-afc4-11e6-8312-3a3fc285780b.png">

**Comment by anthonybrown** [comment]
Ah, I don't use `plug` I'm using `pathogen` or Vundle for my plugins

**Comment by kaylacohn** [comment]
@anthonybrown you should still be able to specify settings, right?

**Comment by anthonybrown** [comment]
I have the same settings like in the thread `autocmd FileType html,css,javascript.jsx EmmetInstall`
and `set filetype: javascript.jsx` 
I don't know how to set them for the plugins if that's what you mean

**Comment by anthonybrown** [comment]
@kaylacohn any suggestions?

**Comment by kaylacohn** [comment]
@anthonybrown can you add a screenshot of your plugin section in your `.vimrc`

**Comment by anthonybrown** [comment]
![screen shot 2016-11-21 at 10 18 05 am](https://cloud.githubusercontent.com/assets/1719818/20488146/ffa6933c-afd3-11e6-909c-35f8d9feb4eb.png)

**Comment by git-toni** [comment]
@anthonybrown You should replace the line importing `vim-jsx` and `emmet-vim` with the ones in @kaylacohn 's vimrc ( see adding `{for...}`).

Also I had to overwrite it on emmet's options
```vim
"In .vimrc
let g:user_emmet_settings = {
\  'javascript.jsx' : {
\      'extends' : 'jsx',
\  },
\}
```

I got it working only this way, extending `jsx` via emmet. Just curious @kaylacohn what version of VIM are you running? 7.4.X here

**Comment by anthonybrown** [comment]
@git-toni, I didn't know you could do that? thanks for the tips
![screen shot 2016-11-21 at 10 35 13 am](https://cloud.githubusercontent.com/assets/1719818/20488777/4a4e43e2-afd6-11e6-80a6-3420891c66e6.png)
so just like this and do a `PluginInstall` with Vundle?

**Comment by git-toni** [comment]
@anthonybrown Actually you don't need to configure `emmet-vim` with those params. Just adding this:

```vim
"In .vimrc
let g:user_emmet_settings = {
\  'javascript.jsx' : {
\      'extends' : 'jsx',
\  },
\}
```
Should work. **AND** don't forget to just in case `rm ~/.vim/view/*`, so VIM resets its view cache.

**Comment by anthonybrown** [comment]
Ok great, I'll try that

**Comment by git-toni** [comment]
@anthonybrown I would add ´{for:['jsx','javascript.jsx']}` to `vim-jsx` so it applies syntax highlighting to both `jsx` and `javascript.jsx` filetypes, to be extra sure :) good luck!

**Comment by kaylacohn** [comment]
@git-toni actually using neovim 0.1.6

**Comment by anthonybrown** [comment]
@git-toni, seems like that did the trick. `emmet-vim` is expanding as it should in my React projects
💥  🍾   🍺

**Comment by kaylacohn** [comment]
@anthonybrown hey i reached out to you via email in regards to helping troubleshoot a syntax highlighting issue with the oceanic next theme

**Comment by anthonybrown** [comment]
I didn't get any emails from you @kaylacohn but, I just went through fixing `OceanicNext`
I just did a search for it and came up with a solution. My problems was `macvim` wasn't picking up the `colorscheme` All I had to do was make a `.gvimrc` file with `colorscheme: OceanicText` to fix my macvim. To get it to work in iterm vim, I added 
```
if (has("termguicolors"))
 set termguicolors
endif
```

**Comment by shampliu** [comment]
Hi guys, so I followed these commands and currently, my emmet-vim will only expand foo.bar to <foo className="bar"> if I set the filetype to jsx but I want to be able to expand it in javascript.jsx files as well because the syntax highlighting is better there. Do you guys have any solutions?

**Comment by mattn** [comment]
Maybe you can enable or disable expanding with configuration. See https://github.com/mattn/emmet-vim/issues/255#issuecomment-261971884

**Comment by shampliu** [comment]
@mattn I tried deleting that line and other combinations but the expansion still doesn't work with javascript.jsx files. 

Currently with these configs, I have my React files ending in ".js" and they get opened as filetype "jsx" and classes are expanded correctly. However I want to open them as "javascript.jsx" files for the syntax highlighting and expand the classes correctly. 

<img width="596" alt="screen shot 2017-02-25 at 2 49 16 pm" src="https://cloud.githubusercontent.com/assets/8483660/23335382/9c1091ec-fb69-11e6-83b2-295066ffd9c3.png">

<img width="399" alt="screen shot 2017-02-25 at 2 48 47 pm" src="https://cloud.githubusercontent.com/assets/8483660/23335386/a0f23666-fb69-11e6-9ca1-f4648298a0df.png">

**Comment by mattn** [comment]
If you want to keep file type as jsx, try to set syntax

```
autocmd FileType jsx set syntax=javascript.jsx
```

**Comment by shampliu** [comment]
@mattn hm that line works for setting the syntax but then I lose the expansion again

**Comment by wbbutterworth** [comment]
@shampliu try let g:user_emmet_settings={'javascript.jsx': {'extends':'jsx'}}

**Comment by shampliu** [comment]
@wbbutterworth I believe that did the trick, thank you!

**Comment by jersearls** [comment]
I had to add this to my .vimrc
`let g:user_emmet_install_global = 0

let g:user_emmet_settings = {
\  'javascript.jsx' : {
\      'extends' : 'jsx',
\  },
\}

autocmd FileType html,css,javascript.jsx EmmetInstall
`

**Comment by Youthink** [comment]
```
:set ft?
```
my result is  ` javascript.jsx`

```
autocmd Filetype javascript.jsx setlocal filetype=jsx
```

It is use for me.

**Comment by evserykh** [comment]
I use Vim with emmet-vim, vim-jsx and a bunch of other plugins (using Vundle).

When I type in any *.html file `.foo>label` then press **Ctrl-Y**+**,** I get:
```
<div class="foo"><label for=""></label></div>
```
When I type in any *.jsx file `.foo>label` - I get the same:
```
 <div class="foo"><label for=""></label></div>
```
If I do `:set ft=jsx` on any *.jsx and then type `.foo>label` the result is:
```
<div className="foo"><label htmlFor=""></label></div>
```
much more better but Vim loses JS syntax highlight.

When I try it with this my .vimrc: 
```
let g:user_emmet_settings = {
\  'javascript.jsx' : {
\      'extends' : 'jsx',
\  },
\}
``` 
I get:
```
<div className="foo"><label></label></div>
```
so label tag doesn't have htmlFor attribute.

Is there a way to make it working properly together? At some point it works in a right way but then something changed.

1) Vim
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 14 2017 18:28:18)
MacOS X (unix) version
...
```

2) emmet-vim
```
ed79a92 - Merge pull request #384 from hpate-omicron/patch-1
```

3) vim-jsx
```
b098827 - Merge pull request #139 from BurningLutz/master (9 weeks ago) <Max Wang>
```

**Comment by mattn** [comment]
You can add default attributes like below.

```vim
\  'javascript.jsx' : {
\    'extends' : 'jsx',
\    'default_attributes': {
\      'label': [{'htmlFor': ''}],
\    }
\  },
```

**Comment by evserykh** [comment]
@mattn, thanks for the reply.
In general, is it expected manner that I have to add default attributes? 

Or it should work out of box? This part should not do the same?
https://github.com/mattn/emmet-vim/blob/master/autoload/emmet.vim#L1975-L1979

**Comment by mattn** [comment]
I don't make sure, it may not work as intended. I'll look into it in later.

**Comment by mattn** [comment]
@c50a326 Already done. But your filetype is not jsx, you need to set configuration.

**Comment by kingluddite** [comment]
I finally got this working and just want to put my notes down in case it helps someone else.

I could get emmet completion working using `ctrl` + `y` AND `,` but not with **tab** and I could never get the **jsx** comments to appear as `{/* */}` instead of `//`

I use **Plug** as my installer (tried the others and like Plug the best)
I hit tab and something was happening and wasn't sure what was the conflict. 

**Here's how you find key conflicts in vim**

`:verbose imap <Tab>`

That lets me see my **supertab** plugin was a conflict so I uninstalled it. I comment it out in my `.vimrc`

`"    Plug 'ervandew/supertab' " Must load before youcompleteme`

I removed all plugins that were commented out using `:PlugClean`
I updated all old plugins using `:PlugUpdate`

I didn't want to have to set my `.js` files to `jsx` every time with `:set ft=jsx`
so I installed **vim-jsx** with adding this to my `.vimrc`:

`Plug 'mxw/vim-jsx'`

**I then ran** 

`:source %
:PlugInstall `

**to install it**

I also added this to my **.vimrc**

`" lets emmet use jsx shortcuts
let g:user_emmet_expandabbr_key='<Tab>'
imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab")
let g:user_emmet_settings = {
\  'javascript' : {
\      'extends' : 'jsx',
\  },
\}

let g:jsx_ext_required = 0`

To make sure you have all the vim plugins installed use `:scriptnames` (make sure you see **emmet** in that list)

I also was using **Ultisnips** and **YouCompleteMe** (this gives me a crazy error all the time and sometimes I shut down Iterm and reopen it and the error goes away --- some server error???) and to get this working I just **disabled** and **uninstalled** them. I would like to get them and **supertab** all working together someday but I'll save that for another day. I think they have conflicts with Emmet?

After all that (above is a culmination of lots of different web pages) I am happy to say emmet is working with **react** and it sees my **.js** files as **jsx** and uses the correct syntax code coloring and my **comments** are **jsx** comments and when I use **emmet** it replaces `class` with `className`. I wish it wasn't such nightmare to get this all working but alas, maybe my pain can somehow save someone else the agony. lol

**Comment by anthonybrown** [comment]
can you share your `.vimrc` with us?

**Comment by anthonybrown** [comment]
@kingluddite can you share your `.vimrc` file ?

**Comment by anthonybrown** [comment]
```
let g:user_emmet_expandabbr_key='<Tab>'
imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab")
```
these lines are inserting some funky stuff, eg:
.conainer exapnds to `.container<Plug>(emmet-expand-abbr)`

I'm I missing something?

**Comment by kingluddite** [comment]
Sorry I updated my post and fixed a typo. Here is my vimrc

https://github.com/kingluddite/dotfiles/blob/master/vimrc

**Comment by anthonybrown** [comment]
how did you get your comments to work?
That doesn't seem to work for me?
I'm using Commentary to comment stuff out, do I just use // or /* */ and hit tab?

**Comment by larrybotha** [comment]
For TypeScript users, to get `className` expansion in both `.ts` and `.tsx`:

```vim
  let g:user_emmet_settings = {
  \ 'typescript' : {
  \     'extends' : 'jsx',
  \ },
  \}
```

**Comment by soywod** [comment]
> For TypeScript users, to get `className` expansion in both `.ts` and `.tsx`:
> 
> ```viml
>   let g:user_emmet_settings = {
>   \ 'typescript' : {
>   \     'extends' : 'jsx',
>   \ },
>   \}
> ```

@larrybotha works well for `.tsx` files, but I had to add also:

```viml
autocmd FileType typescript.tsx EmmetInstall
```

**Comment by EvgeniyMdr** [comment]
Hi, this plugin don't works with file .tsx. Filetype typescriptreact
