### ISSUE TITLE
^M added to wrapped text

### ISSUE THREAD

**Issue by JCodesMN** [mattn/emmet-vim#257]
Hello, all!

Whenever I try to wrap text in emmet I get ^M inside of my brackets twice.

![screen shot 2015-02-25 at 1 21 13 pm](https://cloud.githubusercontent.com/assets/5490881/6378511/7e357466-bcf1-11e4-9000-cf8217586b73.png)
![screen shot 2015-02-25 at 1 22 02 pm](https://cloud.githubusercontent.com/assets/5490881/6378514/813656bc-bcf1-11e4-9884-abaa8713df55.png)

I've wiped my vimrc back to a minimal install and even with just Emmet (no Solarized, no nothing) I'm still getting the same issue.

Any thoughts?

**Comment by mattn** [comment]
I get solved?
