### ISSUE TITLE
Wrapping a line with one key bind

### ISSUE THREAD

**Issue by JCodesMN** [mattn/emmet-vim#260]
Hello all!

I'd love to be able to wrap an entire line in a tag with 1 key bind in vim. Here is what in my vimrc:

![screen shot 2015-02-26 at 10 54 33 am](https://cloud.githubusercontent.com/assets/5490881/6396751/e3ff6536-bda5-11e4-8e6e-2f775e0fabd1.png)

As it's configured now Ctrl-W selects all of the text on the line, but emmet doesn't click in. Any thoughts?

Thanks!

**Comment by mattn** [comment]
Interesting :)

BTW, you can do it with another way.
```vim
nnoremap <SID>line _vg_
nmap <plug>(emmet-expand-abbr-line) <SID>line<plug>(emmet-expand-abbr)
nmap <C-W> <plug>(emmet-expand-abbr-line)
```
This doesn't require setting variable.

**Comment by JCodesMN** [comment]
That is marvelous! Thank you so much!
