### ISSUE TITLE
Add JSX user option

### ISSUE THREAD

**Issue by iansinnott** [mattn/emmet-vim#265]
Can we add an option to support JSX? I know Emmet already has support for `className` expansion but it doesn't always work.

This relates directly to #255 (Thanks for adding that feature btw!). Currently JSX expansion doesn't work with standard `.js` files. Since it's possible to write JSX in files with different extensions (`.js`, `.jsx`, etc) it would be great if there was an option allow JSX expansion regardless of file extension.

Something like:
```vim
let g:user_emmet_jsx = 1
```

**Comment by mattn** [comment]
You need to set `filetype` to `jsx`. Do you mean setup emmet for jsx with `filetype=js`?

**Comment by iansinnott** [comment]
Yes. JSX expansion works for me if I do `:set filetype=jsx`, but then I lose all of my javascript specific Vim configurations including syntax highlighting.

Ideally emmet could do JSX expansion in any filetype. So if you do `:set filetype=javascript` then:

```
div.something
```

Could still turn into

```
<ul className='something'></div>
```

Also

```
label.something[for=some-input]
```

Would turn into

```
<label className='something' htmlFor="some-input"></label>
```

**Comment by mattn** [comment]
How about to set `filetype=javascript.jsx` ?

**Comment by iansinnott** [comment]
Thanks for the tip. I didn't know you could set multiple filetypes like that. Unfortunately it didn't work. Expansion of class to className works if I `:set filetype=jsx` but does not work if I `:set filetype=javascript.jsx`. It also doesn't work for `filetype=jsx.javascript` :confused:

**Comment by archr** [comment]
This works for me:

```
set filetype=javascript.jsx
```

**Comment by duteng** [comment]
I also have this problem. 
The `class` can't transform to `className` 

@iansinnott   did you solved this ?

not work for me：
```
set filetype=javascript.jsx
```
Env: Mac OS 10.10 Vim:7.4(Installed by brew)

**Comment by iansinnott** [comment]
Hey @duteng, actually no I never solved this. It would be worth solving, I just sort of forgot about it... I ended up crating a function that would replace all occurances of `class` with `className`:

```vim
" This is used exclusively for React.js. It will replace all occurances of
" class= with className=
function! FixClassNames()
  :%s/\vclass\=/className\=/g
endfunction
command! FixClassNames call FixClassNames()

```

**Comment by meriadec** [comment]
`set filetype=javascript.jsx` doesn't work for me (Vim 7.4, OSx 10.11)

Also, I think changing filetype for every opened file can't bring to new problem. E.g: Ultisnips snippets doesn't work anymore when changing filetype.

What about having an option like `let g:user_emmet_class_name = "className"` with the default as `"class"`?

Anyway, thx for the work!

**Comment by hew** [comment]
Solved w/ https://github.com/mattn/emmet-vim/issues/255#issuecomment-215796031

**Comment by hew** [comment]
With the advent of CSS modules, it would be nice to have the ability to toggle things like

className=""
className={}
className={``}

:)

**Comment by RicardoRien** [comment]
There is no news on this? Will be awesome write _div.principal_ and have the following output: _className={styles.principal}_
