### ISSUE TITLE
How to replace default code autocompletion?

### ISSUE THREAD

**Issue by alex93ushakov** [mattn/emmet-vim#266]
How to change, for example, default 
```
html:5
```
emmet autocompletion with custom code?

**Comment by antlis** [comment]
You can create custom snippet, and then redefine "html:5". For custom snippet you need to install [webapi-vim](https://github.com/mattn/webapi-vim), then add line to your .vimrc
```vim
let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.custom_snippet.json')), "\n"))
```
After that fill custom_snippet.json with your code, like this
```json
{
  "html": {
    "snippets": {
      "html:5": "your_code"
    }
  }
}
```
Actually there is instruction about that [adding-custom-snippets](https://github.com/mattn/emmet-vim#adding-custom-snippets).
