### ISSUE TITLE
Trigger key not working properly.

### ISSUE THREAD

**Issue by Copser** [mattn/emmet-vim#269]
Hello I am a recent user of vim, and installed emmet-vim because I see it useful for mine django projects, been using it for like a mount or so, it was working fine until yesterday when the trigger key just stopped working.
I have installed emmet and configure it just for html, then i have redefine trigger key like it was written in  Readme.mkd.
I was able to use it like that for some time, and there was no problem's, but all of a sudden mine trigger key start giving me this output, 'html:5^Z', and not generating any html5 pages or any other html code,
when i type 'div.msg>img^Z', keep having that capitol Z whit regular expression key stack on it.
Here is mine stackoverflow question regarding this [problem] (http://stackoverflow.com/questions/30404918/emmet-trigger-key-not-working-properly-in-vim)
Can anyone help me understand what is happening, thank you.

**Comment by mattn** [comment]
do you set `timeoutlen`?

**Comment by Copser** [comment]
Sorry, I was working.
No I do not have it set.

**Comment by mattn** [comment]
What OS do you use? gui? in terminal?

**Comment by Copser** [comment]
I am working on Ubuntu 14.04, mine vim is setup for python/django.

**Comment by Copser** [comment]
I am using pretty much standard Ubuntu terminal, and casting vim from him.

**Comment by Copser** [comment]
@mattn,  I will try reconfigure vim and mine packages,  there is an closed issue on this matter in your repository, so I will try work with that,  thanks.
