### ISSUE TITLE
Customization of inline vs multiline

### ISSUE THREAD

**Issue by gryftir** [mattn/emmet-vim#270]
I'd like the ability to customize inline vs multiline behavior.  

The simplest version of such a customization would be an option to never inline.  A more complex version would allow you to pass a dictionary with tags or attributes for each filetype... so for example in html make divs never be inline.

**Comment by mattn** [comment]
You can modify inline/multiline like below

```
let g:user_emmet_settings = {
   ...
\  'html' : {
\    'inline_elements': '...',
\    'block_elements': '...',
      ...
\  },
```
See https://github.com/mattn/emmet-vim/blob/master/autoload/emmet.vim#L1768-L1770

**Comment by gryftir** [comment]
div is already a block element, but block elements in the base case still become one line.  I want elements without children to become multiple lines, or, alternatively, specified elements without children to become one line.
div.row with expand abbreviation ( <C-Y>, ) becomes  <div class="row"></div>
I want to be able to set it so it becomes 
<div class="row">

</div>

**Comment by tomatosource** [comment]
I would love to see it!

**Comment by mattn** [comment]
I wonder you really want this.

```html
<p>
  <a href="">
    <b>
      <i>
         hello
      </i>
    </b>
  </a>
</p>
```

**Comment by gryftir** [comment]
Yes, that's what I want the option to do.
