### ISSUE TITLE
expandKey issue in Windows Gvim

### ISSUE THREAD

**Issue by DemonCloud** [mattn/emmet-vim#271]
```VimL
let g:user_emmet_expandabbr_key ='<S-Tab>'
```

It can work no ``Normal`` mode. but not work on ``Insert`` mode.

How do I config it

**Comment by mattn** [comment]
I can do it in normal/insert/visual mode.

**Comment by DemonCloud** [comment]
@mattn 

I forget tell you .. I use the [Neocomplete] Plugin ...

Also it cant use with [YouCompleteMe] Plugin 

[My Windows Gvim _vimrc file](https://github.com/DemonCloud/dotfile-YVIM/blob/master/_vimrc)

**Comment by mattn** [comment]
do 
```
:verbose map <s-tab>
```

**Comment by DemonCloud** [comment]
<s-tab> work sucess in Linux Gvim Neovim and Vim

But on Windows. ``:verbose map <s-tab>``

show Like this:
![2015-06-20_022649](https://cloud.githubusercontent.com/assets/7436361/8260091/04a1c50c-16f4-11e5-8531-370d2c4ed08d.png)

it means that no Insert mode <s-tab> config. but my vimrc config like:
![2015-06-20_022849](https://cloud.githubusercontent.com/assets/7436361/8260145/423c784e-16f4-11e5-824b-777f2e725b99.png)

**Comment by DemonCloud** [comment]
Am so Sorry it was my wrong

![2015-06-20_023644](https://cloud.githubusercontent.com/assets/7436361/8260307/4297e6ce-16f5-11e5-85e4-326c664383b6.png)

delimitMate.vim Plugin use this config.....
