### ISSUE TITLE
jade & haml support?

### ISSUE THREAD

**Issue by alex93ushakov** [mattn/emmet-vim#275]

**Comment by mattn** [comment]
haml is supported.

**Comment by alex93ushakov** [comment]
Will jade support be implemented in future?

**Comment by mattn** [comment]
since I'm not master of jade, still not. However it's similar to slim and emmet supporte slim currently. So it may easy to implement.

**Comment by alex93ushakov** [comment]
https://github.com/slm-lang/slm

Does it compatible?

**Comment by mattn** [comment]
i didn't know slm
