### ISSUE TITLE
css (sass and possibly other) abbr expansion bug?

### ISSUE THREAD

**Issue by razvanc87** [mattn/emmet-vim#287]
Does anyone else experience this issue?

If I try doing

    fsty:<c-y>,

I get

    font-style: $cursor$italic$select$;$cursor$

The same goes pretty much with all of the other abbreviations that include `${...}`. This doesn't happen in `HTML`. And I've only checked `css` and `sass`. I don't really have experience that much.

**Comment by mattn** [comment]
could you please show me your vimrc?

**Comment by razvanc87** [comment]
Sure, you can find it [here](https://gist.github.com/razvanc87/edd92cc3e9fe4a45853a#file-nvimrc)

**Comment by mattn** [comment]
What version of vim do you use?

**Comment by razvanc87** [comment]
That was quick :). Well, I'm actually using [neovim](https://github.com/neovim/neovim):

```
NVIM 0.0.0-alpha (compiled Aug 14 2015 07:38:05)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g
 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-u3YDNt/neovim-0.0.0+gi
t201508131520+1809+10~ubuntu15.04.1/build/config -I/build/neovim-u3YDNt/neovim-0.0.0+git201508131520+1809+10~ubuntu15.04.1/src -I/build/neovim-u3YDNt/neovim-0.0.0+gi
t201508131520+1809+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-u3YDNt/neovim-0.0.0+git201508131520+1809+10~ubuntu15.04.1/.deps/usr/include -I/usr/include/luaj
it-2.0 -I/build/neovim-u3YDNt/neovim-0.0.0+git201508131520+1809+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-u3YDNt/neovim-0.0.0+git201508131520+1809+10~ubuntu
15.04.1/.deps/usr/include -I/build/neovim-u3YDNt/neovim-0.0.0+git201508131520+1809+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-u3YDNt/neovim-0.0.0+git20150813
1520+1809+10~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-u3YDNt/neovim-0.0.0+git201508131520+1809+10~ubuntu15.04.1/build/src/nvim/auto -I/build/ne
ovim-u3YDNt/neovim-0.0.0+git201508131520+1809+10~ubuntu15.04.1/build/include
Compiled by buildd@lcy01-11
```

But I wouldn't think that this is the problem... would it? I mean why would it work correctly for `.html` and not `.css` (and the like)?...

**Comment by mattn** [comment]
I tried this on neovim. But I can't reproduced. Could you please trying removing `Plug` lines in your nvimrc until emmet works correctly?

**Comment by razvanc87** [comment]
You mean to go through each of the plugins one by one and switch them off? :)... yah, I'll do that, I just hoped someone else already figured this out :D. Thanks

**Comment by razvanc87** [comment]
Thanks for all your help... it turns out it wasn't any of the plugins but this `set gdefault` option, which I guess also affects the `emmet`'s substitution behavior? Is it possible to use this option with `emmet`? cause I really like the default to be *substitute all matches* instead of *substitute the first match*...

**Comment by mattn** [comment]
I tried gdefault in my previous comment. But not reproduced. Hmm. wired.

**Comment by razvanc87** [comment]
Well, I can see that the `substitute` function in `autoload/emmet.vim` are given the `'g'` flag... so if this `set gdefault` is doing it's job properly this would mean you have the opposite effect of the normal `'g'` flag...

**Comment by mattn** [comment]
I'm trying neovim with gdefault. But I can see your problem.

**Comment by razvanc87** [comment]
maybe it matter if these things are set before or after the `Plug` block?!... don't know, it's weird, I'm trying to substitute those `'g'` flags in the `substitute` function to see if I get a different result...

**Comment by mattn** [comment]
Yes, I'm suspecting some plugins effects.

**Comment by razvanc87** [comment]
Not in my case... I just commented out all of the plugins except `emmet` and with `set gdefault` I get these `$cursor` things all over the place.

**Comment by mattn** [comment]
emmet expect `silent! %s/\$\(cursor\|select\)\$//g` so gdefault shouldn't be problem.

**Comment by razvanc87** [comment]
Well, I just removed the `'g'` flag from that line and now it works as expected with `set gdefault`... so it does indeed work as (from `vim` help):

```vim
		command		'gdefault' on	'gdefault' off	~
		:s///		  subst. all	  subst. one
		:s///g		  subst. one	  subst. all
		:s///gg		  subst. all	  subst. one
```

I mean I find it strange that in your case with `set gdefault` it doesn't affect `emmet`...

**Comment by mattn** [comment]
So how about `%s///gg` ?

**Comment by mattn** [comment]
Hmm, should be checked gdefault option? I'm still confusing why my environment works expected.

**Comment by razvanc87** [comment]
Maybe you have your `gdefault` option set in some file in `ftplugin` or something?

**Comment by razvanc87** [comment]
I just replaced those 2 lines (`silent! %s/\$\(cursor\|select\)\$//g`) in `autoload/emmet.vim` with `execute 'silent! %s/\$\(cursor\|select\)\$//' . (&gdefault ? '' : 'g')` and now it's working as expected with or without `set gdefault`.

But are these the only lines I need to worry about?...

**Comment by razvanc87** [comment]
Does this help?

```diff
diff --git a/autoload/emmet.vim b/autoload/emmet.vim
index 0f793ae..63ba55b 100644
--- a/autoload/emmet.vim
+++ b/autoload/emmet.vim
@@ -108,7 +108,7 @@ endfunction
 function! emmet#expandAbbrIntelligent(feedkey) abort
   if !emmet#isExpandable()
     return a:feedkey
-  endif 
+  endif
   return "\<plug>(emmet-expand-abbr)"
 endfunction
 
@@ -686,11 +686,11 @@ function! emmet#expandAbbr(mode, abbr) range abort
       let pos[2] += 1
       silent! s/\$select\$//
       let next = searchpos('.\ze\$select\$', 'nW')
-      silent! %s/\$\(cursor\|select\)\$//g
+      execute 'silent! %s/\$\(cursor\|select\)\$//' . (&gdefault ? '' : 'g')
       call emmet#util#selectRegion([pos[1:2], next])
       return "\<esc>gv"
     else
-      silent! %s/\$\(cursor\|select\)\$//g
+      execute 'silent! %s/\$\(cursor\|select\)\$//' . (&gdefault ? '' : 'g')
       silent! call setpos('.', pos)
       if col('.') < col('$')
         return "\<right>"
```

**Comment by mattn** [comment]
thanks. I'll try to fix with `try/finally`.

**Comment by mattn** [comment]
Could you please try below?
```diff
diff --git a/autoload/emmet.vim b/autoload/emmet.vim
index 5723801..fcd7f5e 100644
--- a/autoload/emmet.vim
+++ b/autoload/emmet.vim
@@ -108,7 +108,7 @@ endfunction
 function! emmet#expandAbbrIntelligent(feedkey) abort
   if !emmet#isExpandable()
     return a:feedkey
-  endif 
+  endif
   return "\<plug>(emmet-expand-abbr)"
 endfunction
 
@@ -682,20 +682,26 @@ function! emmet#expandAbbr(mode, abbr) range abort
     endif
     let pos = emmet#util#getcurpos()
     let use_selection = emmet#getResource(type, 'use_selection', 0)
-    if use_selection && getline('.')[col('.')-1:] =~# '^\$select'
-      let pos[2] += 1
-      silent! s/\$select\$//
-      let next = searchpos('.\ze\$select\$', 'nW')
-      silent! %s/\$\(cursor\|select\)\$//g
-      call emmet#util#selectRegion([pos[1:2], next])
-      return "\<esc>gv"
-    else
-      silent! %s/\$\(cursor\|select\)\$//g
-      silent! call setpos('.', pos)
-      if col('.') < col('$')
-        return "\<right>"
+    try
+      let l:gdefault = &gdefault
+      let &gdefault = 0
+      if use_selection && getline('.')[col('.')-1:] =~# '^\$select'
+        let pos[2] += 1
+        silent! s/\$select\$//
+        let next = searchpos('.\ze\$select\$', 'nW')
+        silent! %s/\$\(cursor\|select\)\$//g
+        call emmet#util#selectRegion([pos[1:2], next])
+        return "\<esc>gv"
+      else
+        silent! %s/\$\(cursor\|select\)\$//g
+        silent! call setpos('.', pos)
+        if col('.') < col('$')
+          return "\<right>"
+        endif
       endif
-    endif
+    finally
+      let &gdefault = l:gdefault
+    endtry
     let &selection = oldselection
   endif
   return ''
```

**Comment by razvanc87** [comment]
Nice, thanks! :+1:
