### ISSUE TITLE
in jade cursor isn't placed in proper places

### ISSUE THREAD

**Issue by razvanc87** [mattn/emmet-vim#289]
For `.jade` files trying for example `input:c<c-y>,` results in `input(id="", type="checkbox", name="")|`, where `|` is the cursor location after the snippet is inserted. The expected behavior is `input(id="|", type="checkbox", name="|")` to be able to jump around with `<c-y>n` no? In `.html` this behaves correctly.

**Comment by mattn** [comment]
haml seems having same issue

**Comment by razvanc87** [comment]
Thanks!
