### ISSUE TITLE
toggleComment hangs vim

### ISSUE THREAD

**Issue by lagtac** [mattn/emmet-vim#290]
I've installed vim and emmet with pathogen on windows. Following the tutorial everything seems to be working, except toggleComment. The following causes vim to hang:

    <ctrl>-y /

**Comment by mattn** [comment]
Please show me how to reproduce.

**Comment by lagtac** [comment]
type ctrl-y / inside the empty body tag.

**Comment by lagtac** [comment]
type ctrl-y / when the cursor is on "<"

**Comment by mattn** [comment]
could you please show me your vimrc?

**Comment by lagtac** [comment]
set nocompatible
syntax on

set tabstop=4
set shiftwidth=4
set expandtab


filetype plugin indent on

au FileType py set autoindent
au FileType py set smartindent
au FileType py set textwidth=79 " PEP-8

"Enable delete on backspace"
set backspace=2

"Newline without entering insert mode"
nmap <CR> o<Esc>
nmap <S-Enter> O<Esc>


"Statusline flags
"see:
"http://got-ravings.blogspot.gr/2008/08/vim-pr0n-making-statuslines-that-own.html"

set statusline=%t       "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file

"Pathogen
call pathogen#infect()

**Comment by lagtac** [comment]
And these are my loaded scripts:

     ~\_vimrc
     C:\Program Files (x86)\Vim\vim74\syntax\syntax.vim
     C:\Program Files (x86)\Vim\vim74\syntax\synload.vim
     C:\Program Files (x86)\Vim\vim74\syntax\syncolor.vim
     C:\Program Files (x86)\Vim\vim74\filetype.vim
     C:\Program Files (x86)\Vim\vim74\ftplugin.vim
     C:\Program Files (x86)\Vim\vim74\indent.vim
     ~\vimfiles\autoload\pathogen.vim
     C:\Program Files (x86)\Vim\vim74\ftoff.vim
     ~\vimfiles\bundle\emmet-vim\plugin\emmet.vim
     C:\Program Files (x86)\Vim\vim74\plugin\getscriptPlugin.vim
     C:\Program Files (x86)\Vim\vim74\plugin\gzip.vim
     C:\Program Files (x86)\Vim\vim74\plugin\matchparen.vim
     C:\Program Files (x86)\Vim\vim74\plugin\netrwPlugin.vim
     C:\Program Files (x86)\Vim\vim74\plugin\rrhelper.vim
     C:\Program Files (x86)\Vim\vim74\plugin\spellfile.vim
     C:\Program Files (x86)\Vim\vim74\plugin\tarPlugin.vim
     C:\Program Files (x86)\Vim\vim74\plugin\tohtml.vim
     C:\Program Files (x86)\Vim\vim74\plugin\vimballPlugin.vim
     C:\Program Files (x86)\Vim\vim74\plugin\zipPlugin.vim
     ~\Dropbox\webdev\learnjs\mybackbone\vim.session
     C:\Program Files (x86)\Vim\vim74\syntax\javascript.vim
     C:\Program Files (x86)\Vim\vim74\ftplugin\javascript.vim
     C:\Program Files (x86)\Vim\vim74\indent\javascript.vim
     C:\Program Files (x86)\Vim\vim74\syntax\html.vim
     C:\Program Files (x86)\Vim\vim74\syntax\vb.vim
     C:\Program Files (x86)\Vim\vim74\syntax\css.vim
     C:\Program Files (x86)\Vim\vim74\ftplugin\html.vim
     C:\Program Files (x86)\Vim\vim74\indent\html.vim
     C:\Program Files (x86)\Vim\vim74\scripts.vim
     C:\Program Files (x86)\Vim\vim74\syntax\conf.vim
     C:\Program Files (x86)\Vim\vim74\ftplugin\conf.vim
     ~\vimfiles\bundle\emmet-vim\autoload\emmet\util.vim
     ~\vimfiles\bundle\emmet-vim\autoload\emmet.vim
     ~\vimfiles\bundle\emmet-vim\autoload\emmet\lang.vim
     ~\vimfiles\bundle\emmet-vim\autoload\emmet\lang\html.vim
     C:\Program Files (x86)\Vim\vim74\syntax\help.vim
     C:\Program Files (x86)\Vim\vim74\ftplugin\help.vim

**Comment by mattn** [comment]
Ah, probably, you do this in insert mode? right?
