### ISSUE TITLE
lorem expands to <lorem></lorem> instead of lorem text

### ISSUE THREAD

**Issue by pjquinn** [mattn/emmet-vim#291]
p>lorem5 

gives me the following, instead of a paragraph with 5 lorem words:

<p>
    <lorem></lorem>
</p>

Any ideas welcome. thx!

**Comment by pjquinn** [comment]
sorry, should've wrapped it in code block, this is what p>lorem5 gives me:

```

<p>
    <lorem5></lorem5>
</p>

```

**Comment by pjquinn** [comment]
removed other plugins and reinstalled. now it's good. no issue. 
great plugin, thx!

**Comment by mattn** [comment]
BTW, what plugins did you removed?

**Comment by pjquinn** [comment]
via Vundle:
Plugin 'VundleVim/Vundle.vim'
Plugin 'mattn/emmet-vim'
Plugin 'rstacruz/sparkup'
Plugin 'othree/html5.vim'
Plugin 'scrooloose/syntastic'
Plugin 'Valloric/MatchTagAlways'

and matchit.vim manually installed

I ended up removing sparkup completely, but I don't know for sure that that was the problem.
