### ISSUE TITLE
Lorem as attribute value does not expand at all or does incorrectly.

### ISSUE THREAD

**Issue by dNitro** [mattn/emmet-vim#294]
By default lorem(lipsum) is expanded in abbreviations or when it is the first word on the line or is preceded by one or more whitespace characters. So for example trying to insert some dummy text as attribute value doesn't seem to work correctly ( | is cursor location ):

``` html
<meta name="description" content="lorem20|">
```

does not expand at all and the following will expand incorrectly :

``` html
<meta name="description" content="lorem20|"
```

to

``` html
<meta name="description" <content></content>
Ipsum voluptatibus modi consequuntur sapiente exercitationem iste perferendis animi aperiam beatae. Enim aliquid neque quaerat dolore doloremque, illum laboriosam quod!
```

BUT it should be expanded regardless of the preceding character. In other words, in the middle of a word. so everywhere we can have some dummy text. Inserting some dummy text as attribute value or any other place like this that "lorem\d*" is part of context is of utmost importance for fast development. after all we are coders, not copywriters ;)

**Comment by mattn** [comment]
Currently, emmet doesn't support expanding in attribute-value.

**Comment by dNItro** [comment]
Just take a look at http://docs.emmet.io/ ; There is a javascript based browser text editor and if you hit the "try it yourself" button and enter "lorem3" as attribute value it expands correctly. so i think emmet currently support this feature and maybe i just make a request to you to add this feature also to emmet-vim.

**Comment by mattn** [comment]
Yes, I know. This is TODO. :)

On 9/26/15, dNItro <notifications@github.com> wrote:
> Just take a look at http://docs.emmet.io/ ; There is a javascript based
> browser text editor and if you hit the "try it yourself" button and enter
> "lorem3" as attribute value it expands correctly. so i think emmet currently
> support this feature and maybe i just make a request to you to add this
> feature also to emmet-vim.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/emmet-vim/issues/294#issuecomment-143345446


-- 
- Yasuhiro Matsumoto

**Comment by gilmrjc** [comment]
I don't know if this was fixed in a more recent release but I can expand lorem in attributes like this <meta name="description" content="lorem20|"> using <C-y>; instead of <C-y>,

**Comment by mattn** [comment]
Yes, this is a way to do it simplify.

**Comment by dNitro** [comment]
So i think this issue could be closed as **Workaround exists**, use `<C-y>;` instead of `<C-y>,`
