### ISSUE TITLE
"$cursor$" was added at the beginning of the first line

### ISSUE THREAD

**Issue by Jackliu91** [mattn/emmet-vim#296]
I followed this Tutorial:
```
2. Wrap with an Abbreviation

  Write as below.
  ---------------------
  test1
  test2
  test3
  ---------------------
  Then do visual select(line wise) and type '<c-y>,'.
  Once you get to the 'Tag:' prompt, type 'ul>li*'.
  ---------------------
  <ul>
      <li>test1</li>
      <li>test2</li>
      <li>test3</li>
  </ul>
  ---------------------
```
But my result is:
```
$cursor$<ul>
  <li>test1</li>
  <li>test2</li>
  <li>test3</li>
</ul>
```
my vim is Macvim 7.4.712

**Comment by mattn** [comment]
please show me your vimrc.

**Comment by Jackliu91** [comment]
This is my .vimrc file https://gist.github.com/Jackliu91/88414c570cae806e371c

**Comment by mattn** [comment]
Could you please try to comment-out `Plugin` line except emmet-vim?

**Comment by Jackliu91** [comment]
I have tried. But the problem is still there.I don't know why.

**Comment by mattn** [comment]
I tried your vimrc but can't reproduce.

**Comment by Jackliu91** [comment]
Thank you. Maybe it is because I am using the os x 10.11, a preview os.

**Comment by mattn** [comment]
could you please send me the result(set-all.log) to mattn dot jp at gmail dot com ?
```
:redir > set-all.log
:set all
:redir END
```

**Comment by Jackliu91** [comment]
I find the reason:
This is because this setting:
```
set nowrapscan
```

**Comment by mattn** [comment]
Hmm, I can't reproduce in both of wrapscan/nowrapscan...

**Comment by ChaoMai** [comment]
@mattn I got same issue with @Jackliu91.

Same problem occurred after adding `set nowrapscan`.

**Comment by mattn** [comment]
Oh, I cound reproduce just now.

**Comment by mattn** [comment]
How about this?

**Comment by Jackliu91** [comment]
It is fine now. Thank you!
