### ISSUE TITLE
do you know any plugin for jsp tags completion?

### ISSUE THREAD

**Issue by wsdjeg** [mattn/emmet-vim#297]
i want some completion for jsp tags or html tags,

**Comment by mattn** [comment]
add below into your vimrc.
```vim
let g:user_emmet_settings = {
\  'jsp' : {
\      'extends' : 'html',
\  },
\}
```

**Comment by wsdjeg** [comment]
i just use autocmd FileType html,css,jsp EmmetInstall
is it same as what you show me?

**Comment by mattn** [comment]
Probably works well, But some feature of emmet may not work because jsp doesn't exends html in default.

**Comment by wsdjeg** [comment]
ok thank you i will add this into my vimrc.
