### ISSUE TITLE
CSS abbreviations don't work

### ISSUE THREAD

**Issue by raine** [mattn/emmet-vim#305]
![emmet](https://cloud.githubusercontent.com/assets/11027/11145042/5c22527c-8a0a-11e5-9b43-91d1ebf450b8.gif)

As you can see, `m` expands to `m { }` instead of `margin:|`.

What's wrong? I'm hitting <kbd>ctrl+y,</kbd> to expand.

**Comment by mattn** [comment]
Try below

```
body {
 m /* HERE */
}
```
