### ISSUE TITLE
emmet-vim probably doesn't load on win 7 using pathogen

### ISSUE THREAD

**Issue by codenotfound** [mattn/emmet-vim#316]
Hi, 

I'm using emmet-vim at home, but can't install it correctly at work. On Windows 7, using pathogen manager, Vim 7.4

I have this in my _vimrc: imap \<expr\> \<tab\> emmet#expandAbbrIntelligent("\\\<tab>")

And on pressing TAB I get all sorts of errors.
Here's the screenshot with errors: http://i.imgur.com/xCSoLLS.png

When I comment out the imap, default \<c-y\>, doesnt work either (and doesn't print errors though)

What can be the root of this problem?

**Comment by mattn** [comment]
Do you modify cpoptions flag?

**Comment by codenotfound** [comment]
No, I don't even know what that is.

**Comment by codenotfound** [comment]
Just got a new PC, no more problem. Oh well.
