### ISSUE TITLE
Sass/Erb files doesnt recognize emmet

### ISSUE THREAD

**Issue by chocoelho** [mattn/emmet-vim#317]
I'm facing this problem, it should be me doing something wrong. I'm not able to expand html/css tags when editing eruby/sass files.

vim config:

``` vim
" Emmet {
        let g:user_emmet_mode='a'
        let g:user_emmet_install_global = 0
        autocmd FileType html,css,htmldjango,scss,eruby,less EmmetInstall
        imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")
        autocmd FileType html,css,htmldjango,scss,eruby,less imap <buffer> <Tab> <C-Y>, | imap <buffer> <C-N> <C-Y>,
" }
```

Problem:

``` vim
Error detected while processing FileType Auto commands for "scss":
E492: Not an editor command: EmmetInstall
```

**Comment by mattn** [comment]
What plugin manager do you use?

**Comment by chocoelho** [comment]
Plug

**Comment by mattn** [comment]
Hmm, I use vim-plug but can't reproduce.

**Comment by ViOrise** [comment]
> Plug
> 
> On 03/02/2016 12:34 PM, mattn wrote:
> 
> > What plugin manager do you use?
> > —
> > Reply to this email directly or view it on GitHub
> > [#317 (comment)](https://github.com/mattn/emmet-vim/issues/317#issuecomment-191289372).
have the same problem... Do you solve it ? 

Use vim-plug and neovim

**Comment by mattn** [comment]
Try to add `set nocp` in your vimrc.

**Comment by ViOrise** [comment]
![image](https://user-images.githubusercontent.com/41738895/50084644-b9b2af80-0208-11e9-996e-80a5a6f4cb10.png)
it doesn't work

**Comment by mattn** [comment]
Please show me your vimrc

**Comment by ViOrise** [comment]
Cleared my vimrc (and init for nvim) and just install all plugins. Tried to find the error, but can't found it.
Strange, but all works well, in both terminal: vim and nvim 
![image](https://user-images.githubusercontent.com/41738895/50130521-1658ad80-028f-11e9-9b24-c86b387801bb.png)

Txh for your help
