### ISSUE TITLE
Exception not caught when using .snippets_custom.json

### ISSUE THREAD

**Issue by lukelarsen** [mattn/emmet-vim#318]
I've got this in my .vimrc file and it seems to find the .snippets_custom.json file.
`let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.vim/.snippets_custom.json')), '\n'))`

When I use that in my .vimrc I get this error
`E605: Exception not caught: {\n    'variables': {\n        'lang': 'en',\n        'locale': 'en-US',\n        'charset': 'UTF-8',\n        'indentation': '\t',\n        'newline': '\n'\n    },\n\n    'css': {\n        'filters': 'css',\n        'profile': 'css',\n        'snippets': {\n            'test': 'Testing'\n        }\n    }\n} `

That is the content of .snippets_custom.json

Any ideas?

**Comment by mattn** [comment]
Use `"\n"` instead of `'\n'`

**Comment by lukelarsen** [comment]
Thanks for the quick reply. I had that originally. I forgot to change it back when posting here. When I use "\n" I get this error:

`E605: Exception not caught: \{^@\   'variables': {^@\       'lang': 'en',^@\       'locale': 'en-US',^@\       'charset': 'UTF-8',^@\       'indentation': '\t',^@\       'newline': '\n'^@\   },^@\   'css': {^@\       'filters': 'css',^@\       'profile': 'css',^@\       'snippets': {^@\           'test': 'Testing'^@\       }^@\   }^@\} `

**Comment by mattn** [comment]
If using `''` instead of `"\n"`, what do you get?

**Comment by lukelarsen** [comment]
I got some different but kinda similar error. I then put it back to "\n", restarted Vim and doubled checked my .snippets_custom.json file. Looks like I had a syntax error there. After I fixed all those things it seems to be working now. I'm really sorry for wasting your time. Thanks so much for maintaining this!

**Comment by mattn** [comment]
Ah, your snippet file contains backslash at leading of lines? it's not JSON. it's Vim script.

**Comment by lukelarsen** [comment]
Yeah that was part of the problem. It should be JSON. I'd copied it from a Vim script. 

A new issue is that it won't let me override a snippet. I tried to make a snippet for 'clr' and I get 
`E721: Duplicate key in Dictionary: "clr" `

Followed by a long Invalid Expression error.

**Comment by lukelarsen** [comment]
Never mind I found it. I was declaring a custom snippet with the same name twice. I'm lame.
