### ISSUE TITLE
Is there a way to chance "," comma to another key in emmet-vim expansion

### ISSUE THREAD

**Issue by thebearjew** [mattn/emmet-vim#322]
My Vim Leader is the `,` key, and emmet-vim is dependent on the use of the comma key.

Is there a way, short of editing the plugin, to change this key?

**Comment by mattn** [comment]
See `:help emmet-customize-key-mappings`

**Comment by thebearjew** [comment]
Much appreciated. Sorry for redundant issue.

**Comment by mattn** [comment]
No prob :)
