### ISSUE TITLE
E116: Invalid arguments for function <SNR>35_install_plugin

### ISSUE THREAD

**Issue by JuanCrg90** [mattn/emmet-vim#324]
Today i opend a html file and recieved the next message

![screenshot from 2016-03-26 17-16-22](https://cloud.githubusercontent.com/assets/2718753/14062914/8130c096-f376-11e5-8eb0-a5596b43b5ea.png)

I've updated the package and commented the `autocmd FileType html,css EmmetInstall` line in my vimrc file and works, but if i uncomment this, the error appears. should i make another change?

Regards.

**Comment by mattn** [comment]
See https://github.com/mattn/emmet-vim/issues/323
