### ISSUE TITLE
emmet-vim and NeoCommenter issue

### ISSUE THREAD

**Issue by asins** [mattn/emmet-vim#325]
I do not know how to phrase to describe the problem.

I installed the emmet-vim and NeoComplete. There was a problem when you press `ctrl+n` after completion snippet `ctrl+y+,` completion words, bug the outcome is not what I want.

#### e.g.  in xx.html file:

1. `tab<cursor>`   press `ctrl+n` NeoComplete Completion Code : `table<cursor>`
![emmet-vim-neocommenter](https://cloud.githubusercontent.com/assets/898354/14282429/e031f7b6-fb70-11e5-9100-8015ff4b6053.png)
2. press `ctrl+y+,` emmet-vim completion snippet, Output: `<tab><cursor></tab>`. 

I thought it would be `<table><cursor></table>`, but results were not, **why?**

I do not know if this is the problem of emmet-vim or NeoComplete, sorry!

#### In my `.vimrc` file：

```vim
Plug 'mattn/emmet-vim', { 'for': [ 'css', 'html', 'less', 'sass', 'scss', 'xml', 'xsd', 'xsl', 'xslt', 'mustache' ] }
"   Emmet-Vim {{{2
let g:user_emmet_settings = {
\    'variables' : {
\        'lang' : 'zh-cn',
\    },
\    'html' : {
\        'expandos' : {
\            'ol': 'ol>li',
\            'list': 'ul>li*3',
\        },
\        'filters' : 'html',
\        'default_attributes': {
\            'a': {'href': ''},
\            'link': [{'rel': 'stylesheet'}, {'href': ''}],
\        },
\    }
\ }
"   }}}

Plug 'Shougo/neocomplete.vim'
"   NeoComplete {{{2
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Use camel case completion.
let g:neocomplete#enable_camel_case = 1
" Use fuzzy completion.
let g:neocomplete#enable_fuzzy_completion = 1
" 设置缓存目录
let g:neocomplete#data_directory = s:get_cache_dir("neocomplete")
let g:neocomplete#enable_auto_delimiter = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
" Set auto completion length.
let g:neocomplete#auto_completion_start_length = 2
" Set manual completion length.
let g:neocomplete#manual_completion_start_length = 0
" Set minimum keyword length.
let g:neocomplete#min_keyword_length = 3
" buffer file name pattern that disables neocomplete.
let g:neocomplete#sources#buffer#disabled_pattern = '\.log\|\.log\.\|.*quickrun.*\|\.cnx\|Log.txt\|\.user.js'
" buffer file name pattern that locks neocomplete. e.g. ku.vim or fuzzyfinder
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*\|\*unite\*\|Command Line'
let g:neocomplete#sources#buffer#cache_limit_size = 300000
let g:neocomplete#fallback_mappings = ["\<C-x>\<C-o>", "\<C-x>\<C-n>"]

" <TAB>: completion.
" inoremap <expr><TAB>  pumvisible() ? '<C-n>' : '<TAB>'
"   }}}
```

**Comment by mattn** [comment]
Sorry, I'm not user of neocommenter. And I can't find what is neocommenter.
https://www.google.co.jp/search?q=NeoCommenteroCommenter+vim&gws_rd=cr&ei=GbMFV9-PM8iv0gTGobmgDw

**Comment by asins** [comment]
Is NeoComplete，so sorry~

**Comment by mattn** [comment]
Did you close popup window before typing CTRL-Y + , ?

**Comment by asins** [comment]
No, then I press `Ctrl+y+,`, the NeoComplete popup window is open, bug the word is my need.  you can see screenshot. when prompted to shut down press the key(`Ctrl+y+,`)  will be ok.

**Comment by mattn** [comment]
emmet make the expands with word that start of the word until the cursor. but you don't close popup. i.e. cursor doesn't goes end of `table`. then emmet recognize the word is `tab`.

**Comment by asins** [comment]
![image](https://cloud.githubusercontent.com/assets/898354/14403565/9c3cbe94-fe8e-11e5-8857-39d8ea2a4986.png)

you can see screenshot. cursor is in the full-word end `table<cursor>`, popup will not close any additional questions?

**Comment by mattn** [comment]
As I said, you need to close popup at the first.

**Comment by asins** [comment]
add config in my vimrc. more needs one step, bug then solve the problem.

```vim
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
	return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
```

By the way, the method of the README.md to the configuration will not solve the problem.

**Comment by asins** [comment]
add config in my vimrc. more needs one step, bug then solve the problem.

```vim
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
	return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
```

By the way, the method of the README.md to the configuration will not solve the problem.
