### ISSUE TITLE
Expansion not the same to original emmet

### ISSUE THREAD

**Issue by wilmoz** [mattn/emmet-vim#329]
The expansion of this:
form>fieldset>legend+(label>input[type="checkbox"])*3
In emmet-vim:

```html```
<form action="">
  <fieldset>
    <legend></legend>
    <label for=""><input type="checkbox"></label>
    <legend></legend>
    <label for=""><input type="checkbox"></label>
    <legend></legend>
    <label for=""><input type="checkbox"></label>
  </fieldset>
</form>
```

In original emmet (http://docs.emmet.io/ try it yourself) which is
the expected behavior is:

```html```
<form action="">
    <fieldset>
    	<legend></legend>
    	<label for=""><input type="checkbox"></label>
    	<label for=""><input type="checkbox"></label>
    	<label for=""><input type="checkbox"></label>
    </fieldset>
</form>
```

Emmet-vim adds 2 extra times \<legend\> in the markup

**Comment by mattn** [comment]
Ah, it's wrong

**Comment by wilmoz** [comment]
Thank you very much.
