### ISSUE TITLE
Detect pug as well as jade file types

### ISSUE THREAD

**Issue by bdielman** [mattn/emmet-vim#330]
Jade is now changing it's name to [pug](https://github.com/pugjs/pug). Can you update the file detection to look for both pug and jade file types?

**Comment by bdielman** [comment]
Just updated vim-emmet, but the pug filetype still isn't expanding tags correctly.

When I type this: `input` and then `<c-y>` I expect to see: `input(type="")`.

Instead I get: `<input></input>`

**Comment by mattn** [comment]
RIght. Will fix in later.

**Comment by osenvosem** [comment]
@mattn how is the progress? 🤔

**Comment by mattn** [comment]
Try to set ft=jade

**Comment by osenvosem** [comment]
@mattn and I lose the syntax highlighting, anyway this is nothing but a crunch. How about fixing the plugin and close this issue? 🙂

**Comment by mattn** [comment]
please try last change

**Comment by mattn** [comment]
If you still have an issue, please reopen or file new issue.

**Comment by osenvosem** [comment]
@mattn it seems to be working. Thank you for your work. 👍🏻

**Comment by dyllandry** [comment]
Sorry for opening old issue. I am experiencing the same problem. Setting ft to jade fixes the <c-y> issue but removes my syntax highlighting.
