### ISSUE TITLE
Error on curly brace content (javascript)

### ISSUE THREAD

**Issue by zanona** [mattn/emmet-vim#332]
Apparently when using content replacement on tags if there's a curly brace followed by a character, it will ignore the rest of the expression
To replicate:

     script{obj={foo:'bar'};} #stops at first }
     script{foo({foo:'bar'})} #stops at first }
     script{obj={foo:'bar'}}  #works

Expands to:

```html
<script>obj={foo:'bar'</script>
<script>foo({foo:'bar'</script> 
<script>obj={foo:'bar'}</script>
```

**Comment by mattn** [comment]
This is bits difficult to implement. For example, emmet doesn't work with `script{obj={foo:'b}ar'};}`. Please try this on http://docs.emmet.io/

**Comment by mattn** [comment]
FYI, single quote must not work with escaping. because we may use {} like below.
```
{don't expand single quote}
```

**Comment by zanona** [comment]
Thanks @mattn I see that `script{obj={foo:'b}ar'};}` indeed won't work on emmet website as you mentioned. Although `script{obj={foo:'bar'};}` seems to work fine?

**Comment by mattn** [comment]
What the behavior do you expect about below?

```
script{"don't}+div{don't"}
```

**Comment by zanona** [comment]
I believe something like the below?

```html
<script>"don't</script>
<div>don't"</div>
```

Now if I could scape the curly brace like:

    script{"don't\}+div\{don't"}

I would expect something like:

````html
<script>
  "don't}+div{don't"
</script>
````

**Comment by zanona** [comment]
Thanks a lot @mattn!
I'm afraid, there is still an edge case causing errors such:

    script{obj={foo:'${1}'};} 

outputting:

```html
<script>obj={foo:''</script> 
````
instead of: 

```html
<script>obj={foo:'_'};</script>
````

**Comment by mattn** [comment]
fixed.

**Comment by zanona** [comment]
Thanks again @mattn,
Sorry if I am seeming too picky but here's another case where it's returning an error:

    script{${1}}+div{${1}} 

output:

```html
<script>}+div{</script> 
```

expected would be:

```html
<script>_</script>
<div></div>
```

**Comment by mattn** [comment]
please try again

**Comment by zanona** [comment]
@mattn thanks a lot for your work on this!
The paste change works great but then when using with a space like:

    script{${1} foo bar}+div{${1}}

It still outputs

```html
<script> foo bar}+div{</script>
```

instead of
```html
<script> foo bar</script>
<div></div>
```

**Comment by mattn** [comment]
note that this simple parser doesn't work with nested braces

**Comment by zanona** [comment]
Understood! Thanks a lot for all your help @mattn. It seems to be working great now!
Have a great weekend
