### ISSUE TITLE
Error when using parenthesis

### ISSUE THREAD

**Issue by osenvosem** [mattn/emmet-vim#334]
Got an error when using parenthesis. For example: `ul>(li>a)*3`
<img width="989" alt="screen shot 2016-06-07 at 05 04 04" src="https://cloud.githubusercontent.com/assets/6762673/15843830/d4fb678c-2c6d-11e6-9616-e196e3192e2b.png">

**Comment by mattn** [comment]
Could you please try last change?

**Comment by osenvosem** [comment]
@mattn it works well, thank you.
