### ISSUE TITLE
Set trigger key issue 

### ISSUE THREAD

**Issue by DemonCloud** [mattn/emmet-vim#335]
`let g:user_emmet_leader_key='<S-tab>'`

Shift+Tab to trigger emmet

on Windows : its work prefect

on Linux ( Ubuntu 16.04 LTS)  : its not work.

My emmet config : https://github.com/DemonCloud/Aix-Vim/blob/master/aix/.aixplug.conf.vim#L154

在没有更新之前，两个平台都没有问题，可以稳定触发

**Comment by mattn** [comment]
No, `g:user_emmet_leader_key` is prefix key to trigger with next keys.

![](http://go-gyazo.appspot.com/ae64a3aedde3b992.png)

You will probably get expanded html with typing next key. For example `<S-Tab>` + `,`.
Maybe your expected is `g:user_emmet_expandabbr_key` not `g:user_emmet_leader_key`.

Note: I'm not chinese.
