### ISSUE TITLE
JSX attributes assignments with `{}` brackets

### ISSUE THREAD

**Issue by unclechu** [mattn/emmet-vim#337]
I expect this:
`Route[path=/ component={ MainPage }]`
To be expanded to this:
`<Route path="/" component={ MainPage }></Route>`
But it expands to this:
`<Route path="/" component="{" MainPage=""></Route>`
Do I do something wrong or it's not supported?

**Comment by dockletinc** [comment]
It should be 

>  Route[path=/ component="{ MainPage }"]

**Comment by unclechu** [comment]
@dockletinc hmm. It works, but only when `filetype` is `jsx` but not when `filetype` is `javascript.jsx` for example.

**Comment by mattn** [comment]
See this comment. https://github.com/mattn/emmet-vim/issues/350#issuecomment-262968438

**Comment by unclechu** [comment]
@mattn @dockletinc Thanks! Now it's okay.
