### ISSUE TITLE
<cr> on imap

### ISSUE THREAD

**Issue by roberbnd** [mattn/emmet-vim#345]
![screenshot_20161025_130629](https://cloud.githubusercontent.com/assets/4907027/19698268/3c7d861a-9ab4-11e6-8e86-9e8c87b8e921.png)

Do you have idea why I have <cr> like map on insert mode
I use ctrl-m like leader

**Comment by mattn** [comment]
Because your `g:user_emmet_leader_key` is `<cr>`, maybe.

**Comment by roberbnd** [comment]
I have 
let g:user_emmet_leader_key='<c-m>'
This is my init.vim on line 1086
https://github.com/roberbnd/dotfiles/blob/master/init.vim

**Comment by mattn** [comment]
`<c-m>` have same meaning of `<cr>`. please try this.

```
:echo getchar()
```

and type `<cr>`, next

```
:echo getchar()
```

and type `<c-m>`.

**Comment by roberbnd** [comment]
you are right Thanks!
