### ISSUE TITLE
No expansion for javascript.jsx filetype

### ISSUE THREAD

**Issue by barcher** [mattn/emmet-vim#347]
I recently upgraded emmet-vim, and tag expansion no longer seems to be working for `javascript.jsx` filetypes with the error:
```
=emmet#expandAbbr(0,"")
Error detected while processing function emmet#expandAbbr[2]..emmet#lang#type:
line    8:
E716: Key not present in Dictionary: javascript.jsx
```
where the original files are named `*.js`.

vim version: 8.0
OS: OS X 10.11.6

Based on the feedback in [this post](https://github.com/mattn/emmet-vim/issues/255#issuecomment-215796031) I have temporarily added the following to my `.vimrc` (emmet-vim is otherwise vanilla):
```
let g:user_emmet_settings = {
\  'javascript' : {
\      'extends' : 'jsx',
\  },
\}
autocmd FileType html,css,javascript.jsx EmmetInstall
``` 
with no success. Any idea why this is happening, or how to fix it? Thanks in advance 😃

**Comment by barcher** [comment]
Thanks @mattn !

**Comment by rainerborene** [comment]
@mattn doesn't work for me. see here https://asciinema.org/a/41qqabaxqkyk8f5xvfc0poaw0

**Comment by anthonybrown** [comment]
@mattn same here, take a look: https://asciinema.org/a/89oe3bgyaaukz1zpdan5asmwi
