### ISSUE TITLE
emmet will only start working in other file type once I opened a html file.

### ISSUE THREAD

**Issue by hatelove85911** [mattn/emmet-vim#349]
I have emmet install globally in my vimrc.

`let g:user_emmet_install_global = 1
`
I expect to trigger expansion in any file type. But it doesn't work if I start vim and editing js, json, jsx.
It will only start working after I opened a html file. 

I even notice, when I start vim, I don't even have emmet help file loaded. If I type `:help emmet`, it will tell me no help document for emmet. And as above, only after I opened a html file, then the help document will be there.

I have the latest version of emmet vim installed.

**Comment by NHungate** [comment]
If you're using a plugin manager like vim-plug, check to see if you have a `for` statement following emmet vim.

`Plug 'mattn/emmet-vim', { 'for': 'html' }`

This causes it to initialize only when an HTML file has been loaded. Removing it will allow emmet to initialize with any filetype.

**Comment by hatelove85911** [comment]
@NHungate Yes, it's the problem !! Thank you very much!
