### ISSUE TITLE
Elm support

### ISSUE THREAD

**Issue by mblarsen** [mattn/emmet-vim#356]
Would it be possible to implement support for Elm?

```
<div class="item">
  <h1>ABC <span>DEF</span>
  <p>lorem</p>
</div>
```

in Elm:

```
div [ class "item" ]
  [ h1 [] [ text "ABC ", span [] [ text "DEF" ]
  , p [] [ text "lorem" ]
  ]
```

```
node [ comma separated list of attributes ] [ comma separated list of children ]
```

**Comment by mblarsen** [comment]
@mattn I figured it is a matter of implementing `autoload/emmet/lang/elm.vim`. I got somewhere with doing so. But I cannot figure out how to add the `,` between elements when using multiplication, eg. `ul>li*5`. This simply concats the `li`s.

Is there a way to make `emmet#toString` do that?

https://github.com/mattn/emmet-vim/blob/master/autoload/emmet.vim#L199

**Comment by mattn** [comment]
You can implement autoload/emmet/lang/elm.vim. If you set filetype option, the script will be loaded and emmet#lang#elm#toString is called.

**Comment by mblarsen** [comment]
@mattn would it be possible to have commas between elements in `li*3`? Is there an option to handle this or would I need to override `emmet#toString`?

**Comment by mattn** [comment]
You don't need modify emmet#toString(). Just put a file. And you can call emmet#lang#html#parseIntoTree on emmet#lang#elm#parseIntoTree like this.

https://github.com/mattn/emmet-vim/blob/master/autoload/emmet/lang/haml.vim#L6

**Comment by mblarsen** [comment]
@mattn submitted PR — comments, suggestions are welcome. I haven't' written much vim script before.

**Comment by mattn** [comment]
Wow! Great!

**Comment by mattn** [comment]
Merged

**Comment by mblarsen** [comment]
Wow that was quick!
