### ISSUE TITLE
silent mappings

### ISSUE THREAD

**Issue by nhooyr** [mattn/emmet-vim#361]
Emmet mappings print stuff like `=emmet#expandAbbr(0,"")`. would be nice to silence those.

**Comment by wsdjeg** [comment]
@mattn  I use this plugin in SpaceVim, and I also need this feature.  But I am not sure all the people prefer silent mappings.

**Comment by mattn** [comment]
You can remap your self. Use `<plug>(emmet-expand-abbr)`.

**Comment by wsdjeg** [comment]
nice, it works. :+1:

**Comment by mattn** [comment]
closable?

**Comment by nhooyr** [comment]
Can we reopen this? There are like 12 mappings you'd have to remap yourself. Would be much better to silence by default imo.
