### ISSUE TITLE
Config for newlines per tag

### ISSUE THREAD

**Issue by vonpupp** [mattn/emmet-vim#362]
Hello,

I am quite new to emmet and emmet-vim plugin. I have the following line:

    .form-group.form-field>.col-md-3.col-sm-4.text-right>label.control-label{For Person}

Which once expanded leverages to

    <div class="form-group form-field">
        <div class="col-md-3 col-sm-4 text-right"><label class="control-label" for="">For Person</label></div>
    </div>

I was wondering if there is a way to have all tags to start in a new line as this:

    <div class="form-group form-field">
        <div class="col-md-3 col-sm-4 text-right">
            <label class="control-label" for="">
                For Person
            </label>
        </div>
    </div>

The intention behind it is trying to keep everything under 80 columns.

Thank you.

**Comment by tomatosource** [comment]
Any update on this?

**Comment by mattn** [comment]
https://github.com/mattn/emmet-vim/commit/2247b1f457cd677d911c0a233f5e2e75c9ff908e should fix this. if you still have issue, please file new issue.
