### ISSUE TITLE
Single quotes for attributes not working

### ISSUE THREAD

**Issue by shammellee** [mattn/emmet-vim#366]
If I specify single quotes for attributes, the expansion should be single quotes. Instead, the expansion is double quotes…

input | expected output | actual output
------|---------------------|----------------
`p[foo='bar']`|`<p foo='bar'></p>`|`<p foo="bar"></p>`

**Comment by mattn** [comment]
set `quote_char` to `'`.

**Comment by shammellee** [comment]
Could you be a little more clear? How do I set `quote_char` to `'` exactly?

**Comment by mattn** [comment]
if you want to set it for html, please try to set like below.

```vim
    let g:user_emmet_settings = {
    \  'html' : {
    \    'quote_char': "'",
    \  },
    \}
```

**Comment by shammellee** [comment]
Cool, and how do I enable single quotes for .js and .jsx files?

**Comment by shammellee** [comment]
Never mind, I figured it out. For anyone else wondering…

```vim
let g:user_emmet_settings = {
\    "html": {
\        "quote_char": "'"
\    }
\    ,"javascript.jsx": {
\        "extends": "jsx"
\        "quote_char": "'"
\    }
\}
```

**Comment by mattn** [comment]
Still have issue?

**Comment by rom-dos** [comment]
> Never mind, I figured it out. For anyone else wondering…
> 
> ```viml
> let g:user_emmet_settings = {
> \    "html": {
> \        "quote_char": "'"
> \    }
> \    ,"javascript.jsx": {
> \        "extends": "jsx"
> \        "quote_char": "'"
> \    }
> \}
> ```

Just to clarify, I think there should be a comma after `"extends": "jsx"` -- otherwise this solved the issue for me!
