### ISSUE TITLE
How can I escape a dollar sign? (for templating engines)

### ISSUE THREAD

**Issue by partounian** [mattn/emmet-vim#367]
I have tried ```\$``` and  ```\\$```, but they both end up showing as a number. I currently am trying to use div[value="{{ $option }}"] these tags and similar ones come up often with front-end templating engines, and I am curious if we can escape them in emmet-vim. 

Thanks for the amazing plugin!

**Comment by mattn** [comment]
set `dollar_expr` off.

``` vim
  let g:user_emmet_settings = {
  \  'your-filetype' : {
  \    'extends' : 'html',
  \    'dollar_expr': 0,
  \  },
  \}
```

**Comment by partounian** [comment]
Thanks, I'll keep that in mind, but is there a one-liner I can use when I'm in the middle of programming instead of that global option?

**Comment by mattn** [comment]
You can put the code above into your .vimrc.
