### ISSUE TITLE
E121 undefined variable

### ISSUE THREAD

**Issue by conseal** [mattn/emmet-vim#370]
Hi everyone,

I have an issue with the plugin and would like to ask you for help. 
I already wrote a stackoverflow question because I thought I would be the better place in case the issue is not related to emmet directly but to vim-plug. But it was commented that I should post here, so ...

Anyway, I am just linking here to my [stackoverflow question ](http://stackoverflow.com/questions/43842309/emmet-vim-plugin-wont-work-after-restart)  and hope that is okay for you.

Thank you very much for your time and help!
Thomas

**Comment by mattn** [comment]
your setting seems to be wrong. g:emmet_html5 is defined in plugin/emmet.vim

**Comment by conseal** [comment]
The error was my fault: I found out I had corrupted the .vim-file by some stupid operation. I am sorry for the inconvenience! This issue can be closed.
