### ISSUE TITLE
customization on emmet's snippets.json file

### ISSUE THREAD

**Issue by yufeiluo** [mattn/emmet-vim#373]
ENV:debian+vim+emmet.

1.no backslah at the end of tag when to expand abbreviation

Here is link abbreviation on my .vim/snippets.json file.

    "link": "<link rel=\"stylesheet\" href=\"\" />",

When to expand `link` in emmet ,i get the below output:

    <link rel="stylesheet" href="">

Why can't get 

    <link rel="stylesheet" href="" /> 

as output?

2.fail to customize script tag

I expect to expand `script` as `<script src="" type="text/css"></script>`
    sudo vim .vim/snippets.json
    "script": "<script !src=\"\">",

2.1 What does ! here mean?
2.2  to rewrite 

    "script": "<script !src=\"\">",
 
as     

    "script": "<script src=\"\" type=\"text/javascript\">",

It take no effect when to reboot vim.
No `<script src="" type="text/css"></script>` as expand of `script`.

**Comment by mattn** [comment]
set `let g:emmet_html5 = 0`

**Comment by yufeiluo** [comment]
vim  .vimrc
set let g:emmet_html5 = 0
To restart  vim.   
E518: Unknown option: let

**Comment by yufeiluo** [comment]
vim .vimrc
let g:emmet_html5 = 0

solved
