### ISSUE TITLE
Why  ul>li*4|s take no effect on my pc?

### ISSUE THREAD

**Issue by yufeiluo** [mattn/emmet-vim#376]
The abbreviation `ul>li*4|s` was expanded into 
 
```
 <ul>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>
```
instedd of 

`<ul><li></li><li></li><li></li><li></li></ul>`
The filter |t |c |e are on good status.    
What is the matter for my emmet-vim?  
How to fix it?

**Comment by mattn** [comment]
https://docs.emmet.io/filters/#single-line-s

`s` is single-line filter.

**Comment by yufeiluo** [comment]
restart  vim, issue solved.
