### ISSUE TITLE
Bug with jsx object attributes

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [mattn/emmet-vim#377]
Hello,

Here is what I have

`input+div[style={{height: '100px'}}]`

it is transformed to:
```
      <input />
      <div style="{{height:"></div>
```

and I expect:

```
      <input />
      <div style={{height: '100px'}}></div>

```

Am I missing something ?

**Comment by mattn** [comment]
Why not `input+div[style="height: '100px'"]`?

**Comment by GuillaumeLeclerc** [comment]
This is jsx. And this is forbidden. Moreover it would not work for custom components.


Envoyé depuis mon smartphone Samsung Galaxy.
null

**Comment by mattn** [comment]
Well, I got your expected with `input+div[style="height: '100px'"]` in filetype=jsx.

**Comment by GuillaumeLeclerc** [comment]
[![asciicast](https://asciinema.org/a/xgWjR8BldNBLaxGzrmHX49hqG.png)](https://asciinema.org/a/xgWjR8BldNBLaxGzrmHX49hqG)

**Comment by mattn** [comment]
What? what the result is wrong? type attribute?

**Comment by GuillaumeLeclerc** [comment]
This is definitely not valid JSx

Here is the expected output (see my first message)
```
      <input />
      <div style={{height: '100px'}}></div>
```
