### ISSUE TITLE
In Elm multiple dots do not generate spaces for classes

### ISSUE THREAD

**Issue by nthhisst** [mattn/emmet-vim#382]
Within HTML I tested

> div.myClass1.myClass2

producing the correct behavior:
`<div class="myClass1 myClass2"></div>`

Though in Elm, using the same syntax

> div.myClass1.myClass2 

produces:
`div [ class "myClass1.myClass2" ] []`

where I expected
`div [ class "myClass1 myClass2" ] []`

I also tried emmet's custom attribute syntax

> div [class="myClass1 myClass2"]

which then generates the same elm code as above:
`div [ class "myClass1.myClass2" ] []`

Thanks.

**Comment by bushman77** [comment]
Html.Attributes.class "class1 class2"
