### ISSUE TITLE
Question: How to expand css in JSX file?

### ISSUE THREAD

**Issue by samumist** [mattn/emmet-vim#388]
When I try to expand css abbreviation in a `.jsx` file, it only expands like html tag. For example:

```
m10<trigger>
<m10></m10>

desired result:
margin: 10px;
```

I'm wondering if this could be done and how?
Many thanks

**Comment by danbruegge** [comment]
Currently my workaround is that i have mappings that toggle between `:set ft=css` and `:set ft=javascript.jsx`.

**Comment by samumist** [comment]
Thanks @danbruegge for the workaround.

**Comment by danbruegge** [comment]
```vim
function! ToggleJsxCssFt()
    if &filetype == 'javascript.jsx'
        set filetype=css
    else
        set filetype=javascript.jsx
    endif
endfunction

nnoremap <leader>T :call ToggleJsxCssFt()<cr>
```
Forgot to put the code into the comment. ;) Its not the best solution for for a quick workaround it will do the job.

**Comment by mattn** [comment]
If you still have issue for jsx file, please try to fix with this issue? https://github.com/mattn/emmet-vim/issues/350
