### ISSUE TITLE
Getting html version of expansions for both javascript and jsx files

### ISSUE THREAD

**Issue by kapv89** [mattn/emmet-vim#406]
Screenshot attached, a JSX file with sample html tags expanded from their respective abbreviations
![screenshot from 2018-02-20 01-04-34](https://user-images.githubusercontent.com/1023032/36394382-0cf9f502-15da-11e8-8327-8b11bfa10ddd.png)

**Comment by kapv89** [comment]
My end goal is to make vim-emmet work properly javascript and typescript files. I don't think anybody has actually used a JSX extension in 1-2 years.

**Comment by mattn** [comment]
Could you please try to fix with this issue? https://github.com/mattn/emmet-vim/issues/350
