### ISSUE TITLE
Issue with lorem ipsum expansion creating junk tags

### ISSUE THREAD

**Issue by khamer** [mattn/emmet-vim#423]
On the latest version, instead of `.foo>lorem3` expanding to
```html
<div class="foo">
    Elit quas at?
</div>
```

It expands to
```html
<div class="foo">
    <lorem3>
        Ipsum maxime error
    </lorem3>
</div>
```

In some situations, it create an extra `<span>` tag instead of a lorem tag. Using git bisect, it looks like this problem was introduced in commit fb31b5. I'm not exactly sure what the fix is; maybe you can make more sense of this. Thanks!

**Comment by mattn** [comment]
This should be fixed in https://github.com/mattn/emmet-vim/commit/e7dd13a75077aaafa5fc78a205f57e50d816f310
