### ISSUE TITLE
emmet#imageSize() doesn't seem to work

### ISSUE THREAD

**Issue by yedhink** [mattn/emmet-vim#425]
i just tried the <c-y>i shortcut for invoking the imageSize() function  in emmet. But nothing happens.   

I specifically moved the cursor to the img tag and did the above. in insert mode nothing happens. i tried the same in normal mode. i see "call emmet#imageSize()" showing up in command line, but nothing happens.  

Tried to invoke the function  on this text :- 
        ```<img src="foo.png">```

**Comment by mattn** [comment]
do you have xxd?

**Comment by yedhink** [comment]
no i dont. if you would tell me how to get that then i could provide it here.

**Comment by yedhink** [comment]
`00000140: 2020 2020 2020 2020 3c69 6d67 2073 7263          <img src
00000150: 3d22 666f 6f2e 706e 6722 3e0a 2020 2020  ="foo.png">.    
`
is this what you were looking for?

**Comment by mattn** [comment]
No, could you please send me the image file?

**Comment by yedhink** [comment]
Thank you for asking this :D. it's working now. my bad. the name of orginal image file and the name that i used in the code were not matching. when i used the correct name in the code it worked as intended. Thanks for your time.
