### ISSUE TITLE
Can't parse formatted snippets.json

### ISSUE THREAD

**Issue by yibhou** [mattn/emmet-vim#435]
vimrc:
let g:user_emmet_settings = webapi#json#decode(join(          
      \ readfile(expand('$HOME/.snippets.json')), '\n'))

Error detected while processing function webapi#json#decode:
line    8:
E605: Exception not caught: {\n  "variables": { "lang" : "cn", "locale": "en-US" }\n}

can not parse this :
{
     "variables": { "lang" : "cn", "locale": "en-US" }
 }
but  successful below: (in one line code)
{"variables": { "lang" : "cn", "locale": "en-US" }}

**Comment by mattn** [comment]
Please use "\n" instead of '\n'
