### ISSUE TITLE
Object lookup in JSX className expression

### ISSUE THREAD

**Issue by srounce** [mattn/emmet-vim#436]
## What is wrong
Cannot address sub-keys via JSX className (`element.{object.className}`) in the same way we are with attributes.

### (Works) Value:
```
%div.{cssModuleClassName}
```
yields
```
<div className={cssModuleClassName}></div>
```
---
### (Works) Object lookup in attributes
```
%div[className={styles.cssModuleClassName}]
```
yields
```
<div className={styles.cssModuleClassName}></div>
```
---
### (Doesn't work) Object lookup in className
```
%div.{styles.cssModuleClassName}
```
yields
```
<div className="{styles cssModuleClassName"></div>
```
expected
```
<div className={styles.cssModuleClassName}></div>
```

**Comment by mattn** [comment]
Could you please add `what is wrong` in description?

**Comment by srounce** [comment]
> Could you please add what is wrong in description?

Ugh didn't realise I'd overwritten the post intro.

**Comment by srounce** [comment]
I don't think this is resolved.

I tried the latest version and current behaviour is as follows:

```javascript
%div.{styles.lolwut}
```
yields:
```html
<div className={styles lolwut}></div>
```
expected:
```html
<div className={styles.lolwut}></div>
```

**Comment by mattn** [comment]
I don't understand where's differences in your previous comment hields/expected.

**Comment by mattn** [comment]
Which editor works with such behavior?

**Comment by srounce** [comment]
I'm using (neo)vim. 
I only use emmet-vim so I don't know if any other zencoding/emmet-like plugins implement this behaviour correctly for JSX classNames for other editors.
