### ISSUE TITLE
Bad Completion in Pug Files

### ISSUE THREAD

**Issue by dyllandry** [mattn/emmet-vim#448]
I am having a similar problem as https://github.com/mattn/emmet-vim/issues/330#issuecomment-257091820. In pug files vim-emmet <c-y> assembles html syntax instead of pug syntax. Setting ft to jade fixes the syntax problem but removes pug syntax highlighting.

**Comment by mattn** [comment]
Closed by https://github.com/mattn/emmet-vim/commit/ae7d31f29080ad18073dda3530582dacb18475e6
