### ISSUE TITLE
Is it possible to make attributes into JSX props?

### ISSUE THREAD

**Issue by faurehu** [mattn/emmet-vim#449]
This has been done for Atom [1] but I'd like to have it in vim too.

I would like to write something like:

`MyComp[prop=myFunction title="title" number=42]`

and have it become:

`<MyComp prop={myFunction} title="title" number={42}/>`

I wonder if this is possible with any customisation of the current release or this would require some sort of update from the plugin code.

Many thanks.

[1] https://github.com/iJigg/emmet-jsx-props

**Comment by mattn** [comment]
This is same behavior on official emmet.

https://docs.emmet.io/
