### ISSUE TITLE
JS and PHP expand issue

### ISSUE THREAD

**Issue by Simounet** [mattn/emmet-vim#453]
Hi there,
Since ae7d31f2, I can't use expands on PHP and JS files anymore. In both cases, the type from https://github.com/mattn/emmet-vim/blob/master/autoload/emmet.vim#L518 returns `html`.
Have a nice day.

**Comment by mattn** [comment]
What file type do you use? `php` ? I can expand html in php file.

**Comment by Simounet** [comment]
Yep, `test.php` for example. I've added some custom snippets from my `.vimrc` file. Using Vim 7.4.1689.

**Comment by mattn** [comment]
Could you please show me your custom configuration?

**Comment by Simounet** [comment]
Of course:
```
Bundle 'mattn/emmet-vim'
"let g:user_emmet_expandabbr_key = '<C-Y>,'
"let g:user_emmet_expandabbr_key = '<tab>'
let g:user_emmet_expandabbr_key = '<C-e>'
" " Emmet custom settings
let g:user_emmet_settings = {
\  'php' : {
\    'extends' : 'html',
\    'filters' : 'c',
\    'snippets': {
\      'pr': "echo '<pre>' . print_r( |, true ) . '</pre>';",
\      'e': 'echo |;',
\      'vd': 'var_dump(|);'
\    }
\  },
\  'javascript' : {
\    'snippets': {
\      'cl': 'console.log( | );',
\      'cd': 'console.dir( | );',
\      'ci': 'console.info( | );',
\      'cde': 'console.debug( | )'
\    }
\  }
\}

nnoremap <Leader>as :Emmet as<CR>"+Pa\|
nnoremap <Leader>deb :Emmet as<CR>
```

**Comment by M4R7iNP** [comment]
Happens for me too. I _only_ get HTML snippets in PHP files. [This is my emmet config](https://github.com/M4R7iNP/dotfiles/blob/master/.vimrc#L201-L206). Try `:Emmet phphead` in a PHP file.

Nice plugin btw, I use it daily :)
