### ISSUE TITLE
Responsive technical documentation page for the tutorial at https://github.com/mattn/emmet-vim/blob/master/TUTORIAL

### ISSUE THREAD

**Issue by FidelVe** [mattn/emmet-vim#470]
I created a simple responsive page for the tutorial at https://github.com/mattn/emmet-vim/blob/master/TUTORIAL.

I made it with a style resembling the https://emmet.io/ website in case @mattn might want to use it on that site. After finishing I found that there's already an official doc with a more in-depth explanation at https://docs.emmet.io/. 

So, anyway here's the [repo](https://github.com/FidelVe/emmet-vim-tutorial) and the [live page](https://fidel.engineer/emmet-vim-tutorial/), feel free to use it if you want to.

:+1:

**Comment by mattn** [comment]
Wow! Thanks!

**Comment by FidelVe** [comment]
It was my pleasure, I really like the emmet.vim plugin, I think it is amazing, I'm just glad I can collaborate back with a little something!.
