### ISSUE TITLE
Question: embed selected lines

### ISSUE THREAD

**Issue by Char-Aznable** [mattn/emmet-vim#475]
Say I have visually selected:
```
test1.png
test23.png
testCD.png
```
Is there any easy way to make it into:
```
<embed src="test1.png">
<embed src="test23.png">
<embed src="testCD.png">
```
I tried something like embed* or embed src* but none work.

**Comment by mattn** [comment]
1. Select 3 lines
2. `<c-y>` + `,`
3. input `embed[$#]*` on the prompt
