### ISSUE TITLE
scss custom snippets not working

### ISSUE THREAD

**Issue by santimirandarp** [mattn/emmet-vim#479]
Scss snippets do not appear on the document. For example, if I write footerVariables + C-z, 
then I get 
footerVariables{ 

}

css, sass, scss are all installed or at least the files are under /lang/
html custom snippets is working as expected.

I am sharing an example file here: https://pastebin.com/HDVmTrNW

I don't know what else to try or where to read.

**Comment by wiznia** [comment]
If the properties are not working, take into account that you need to be inside the curly brackets for them to work. For example, `mt100` will translate to `margin-top: 100px` but you have to be inside your class definition for it to work.
