### ISSUE TITLE
Recent commit broke syntax highlighting for Ruby (possibly others)

### ISSUE THREAD

**Issue by brett-novu** [mattn/emmet-vim#503]
Commit 9c526a43d63f22dfbf79ea1026f2c0b0b6515fae broke syntax highlighting in Ruby:

<img width="248" alt="Screen Shot 2020-10-21 at 9 58 46 AM" src="https://user-images.githubusercontent.com/50113881/96738710-9c127c00-1384-11eb-9563-0b9d00cecffa.png">

Commit a46a282c5e817e83e3dc918dcf954e9ed6affb5c:

<img width="271" alt="Screen Shot 2020-10-21 at 10 02 16 AM" src="https://user-images.githubusercontent.com/50113881/96738732-a3d22080-1384-11eb-9da6-acd8bbd50233.png">

**Comment by bowmanmike** [comment]
I think it broke Elixir too.

Expected:
![image](https://user-images.githubusercontent.com/15827207/96747589-71c9ba00-1396-11eb-9ed6-8fd660bf190a.png)

Actual:
![image](https://user-images.githubusercontent.com/15827207/96747625-7d1ce580-1396-11eb-9763-dec806a88e05.png)

**Comment by mattn** [comment]
Fixed in last change. Could you please try it.

**Comment by glenbray** [comment]
fixed for me. Thanks!

**Comment by mattn** [comment]
Thank you

**Comment by brett-novu** [comment]
Excellent!  Works for me!  Thank you!!!
