### ISSUE TITLE
"key not found in dictionary" on first use

### ISSUE THREAD

**Issue by sma-ops** [mattn/emmet-vim#510]
I installed emmet-vim via pathogen, and then trying anything, e.g., 'ul>li' followed by `<c-y>,` in an xml file, I get:

=emmet#expendAbbr(0,"")
Error detected while processing function emmet#expandAbbre[151]..emmet#toString[40]..emmet#leng#html#toString:
line 134:
E716: Key not present in Dictionary: empty

I'm not used to debug these error messages, but does line 134 refers to bundle/emmet-vim/autoload line 134 starting at the file start, or using function emmet#toString as offset? 
The former would be 'let lhs += map(keys(rhs), '{v:val : rhs[v:val]}')' in function emmet#mergeConfig
The latter would be 'let extends = emmet#lang#getExtends(a:type)' in emmet#toString

In both cases I have no clue what is amiss.

**Comment by mattn** [comment]
I can't reproduce this. What version of Vim do you use?

**Comment by sma-ops** [comment]
I'm sorry, it dawned on my that the initial download step is not just an alternative installation method, but needed prior to any of the various ways of installing - obviously ...
