### ISSUE TITLE
If the line break will not be reflected.

### ISSUE THREAD

**Issue by nabezokodaikon** [mattn/emmet-vim#517]
If the line break will not be reflected.

OK
```vim
autocmd FileType
\ html,javascript,typescript,javascriptreact,typescriptreact
\ EmmetInstall
```

NG
```vim
autocmd FileType
\ html,
\ javascript,
\ typescript,
\ javascriptreact,
\ typescriptreact
\ EmmetInstall
```

I want to set up in line break, as I will be long.

**Comment by mattn** [comment]
This is not a bug of emmet-vim but probably you should join the tokens with backslash without space characters between commas.

**Comment by nabezokodaikon** [comment]
Understood. Thank you
