### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Iamafnan** [mattn/emmet-vim#534]
Is there any way to manually expand any emmet abbreviation?

**Comment by Rz-Rz** [comment]
Yes its in the docs, you can use <C-Y> or you can specify your own key maps like so by writing this in your .vimrc or init.vim let g:user_emmet_leader_key=','  This remaps to the coma, if you press ,, it will expand your abbrev

**Comment by Iamafnan** [comment]
I am trying to make a plugin which used emmet so can you tell me how can I manually expand

**Comment by ns740** [comment]
i think the function `emmet-expand-abbr` does what you want 
(you should have it if you install the `mattn/emmet-vim` plugin).

**Comment by Iamafnan** [comment]
Thanks
