### ISSUE TITLE
Unknown error while trying to parse custom snippets

### ISSUE THREAD

**Issue by Tagvi** [mattn/emmet-vim#535]
I added this to my `init.vim` on line 45
```vim
let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.snippets.json')), "\n"))
````
and inside the .snippets.json is
```JSON
 {
 "script": "<script type='module' src='${0}'> </script>"
 }
```
And I assume this is enough config for it to work. Next up I get this error message:
`Error detected while processing /home/tagvi/.config/nvim/init.vim:
line   45`
(Nothing else)

I have the web API installed.
Arch Linux
Kernel: 5.10.87-1-lts
Neovim 0.6.0-1

Ways to reproduce:
Edit any file using nvim

**Comment by Tagvi** [comment]
Looks like I didn't have web-api properly installed

**Comment by mattn** [comment]
FYI, vim have json_decode()

2022年1月7日(金) 21:50 Otar Natsvaladze ***@***.***>:
