### ISSUE TITLE
support Compatible with treesitter

### ISSUE THREAD

**Issue by kola-web** [mattn/emmet-vim#557]
After checking the source code, I found that after enabling tresitter html
  let type = synIDattr(synID(max([pos[1], 1]), max([pos[2], 1]), 1), 'name')
The return value of

**Comment by mattn** [comment]
Please show me your git diff ?

**Comment by kola-web** [comment]
![image](https://github.com/user-attachments/assets/6d5dcc09-68cc-406b-94b9-165f68bc483f)
in neovim enable treesitter html
![image](https://github.com/user-attachments/assets/ea292dc6-165a-48fd-915c-f2924508e252)
in neovim disable treesitter html (TSBufDisable highlight)
![image](https://github.com/user-attachments/assets/94fdfa35-8a8d-4ba6-be20-49fd1d28ca10)

**Comment by kola-web** [comment]
![image](https://github.com/user-attachments/assets/b8b5a184-2617-4a98-ad10-1203a33b8825)
I did this temporarily, but the performance dropped a lot after the file exceeded 200 lines
